package com.exe.vocafy_BE.initializer

import com.exe.vocafy_BE.enum.LanguageCode
import com.exe.vocafy_BE.enum.LanguageSet
import com.exe.vocafy_BE.enum.PartOfSpeech
import com.exe.vocafy_BE.enum.SyllabusSourceType
import com.exe.vocafy_BE.enum.SyllabusVisibility
import com.exe.vocafy_BE.model.entity.Syllabus

object JlptN4Seed : SyllabusSeedModule {
    override val key: String = "jlpt-n4"

    override fun seed(context: SyllabusSeedContext): Syllabus = with(context) {
        val n4Syllabus = syllabusRepository.save(
            Syllabus(
                title = "JLPT N4 Intermediate",
                description = "Intermediate Japanese vocabulary for JLPT N4 level. Covers more complex grammar and expressions.",
                imageBackGroud = "https://apps.apple.com/bh/app/n4-jlpt-basic-edition/id6748867272",
                imageIcon = "https://www.japanesepod101.com/lesson-library/jlpt-n4-recommended-course",
                totalDays = 45,
                languageSet = LanguageSet.EN_JP_VI,
                studyLanguage = LanguageCode.JA,
                visibility = SyllabusVisibility.PUBLIC,
                sourceType = SyllabusSourceType.CURATED,
                createdBy = owner,
                active = true,
                category = generalCategory
            )
        )

        val n4TopicSeeds = listOf(
            TopicSeed(
                title = "Family & Relationships",
                description = "Vocabulary about family members and relationships.",
                totalDays = 7,
                courses = listOf(
                    CourseSeed(
                        title = "Family Members",
                        description = "Words for family members.",
                        vocabularies = listOf(
                            VocabSeed("家族", "かぞく", "family", "family", PartOfSpeech.NOUN),
                            VocabSeed("両親", "りょうしん", "parents", "parents", PartOfSpeech.NOUN),
                            VocabSeed("父", "ちち", "father", "father (humble)", PartOfSpeech.NOUN),
                            VocabSeed("母", "はは", "mother", "mother (humble)", PartOfSpeech.NOUN),
                            VocabSeed("お父さん", "おとうさん", "father", "father (polite)", PartOfSpeech.NOUN),
                            VocabSeed("お母さん", "おかあさん", "mother", "mother (polite)", PartOfSpeech.NOUN),
                            VocabSeed("兄", "あに", "older brother", "older brother (humble)", PartOfSpeech.NOUN),
                            VocabSeed("姉", "あね", "older sister", "older sister (humble)", PartOfSpeech.NOUN),
                            VocabSeed("弟", "おとうと", "younger brother", "younger brother", PartOfSpeech.NOUN),
                            VocabSeed("妹", "いもうと", "younger sister", "younger sister", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Extended Family",
                        description = "Extended family members.",
                        vocabularies = listOf(
                            VocabSeed("祖父", "そふ", "grandfather", "grandfather (humble)", PartOfSpeech.NOUN),
                            VocabSeed("祖母", "そぼ", "grandmother", "grandmother (humble)", PartOfSpeech.NOUN),
                            VocabSeed("おじいさん", "おじいさん", "grandfather", "grandfather (polite)", PartOfSpeech.NOUN),
                            VocabSeed("おばあさん", "おばあさん", "grandmother", "grandmother (polite)", PartOfSpeech.NOUN),
                            VocabSeed("叔父", "おじ", "uncle", "uncle", PartOfSpeech.NOUN),
                            VocabSeed("叔母", "おば", "aunt", "aunt", PartOfSpeech.NOUN),
                            VocabSeed("いとこ", "いとこ", "cousin", "cousin", PartOfSpeech.NOUN),
                            VocabSeed("親戚", "しんせき", "relative", "relative", PartOfSpeech.NOUN),
                            VocabSeed("孫", "まご", "grandchild", "grandchild", PartOfSpeech.NOUN),
                            VocabSeed("子供", "こども", "child", "child", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Relationships",
                        description = "Relationship vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("友達", "ともだち", "friend", "friend", PartOfSpeech.NOUN),
                            VocabSeed("親友", "しんゆう", "best friend", "best friend", PartOfSpeech.NOUN),
                            VocabSeed("恋人", "こいびと", "lover", "lover/partner", PartOfSpeech.NOUN),
                            VocabSeed("彼氏", "かれし", "boyfriend", "boyfriend", PartOfSpeech.NOUN),
                            VocabSeed("彼女", "かのじょ", "girlfriend", "girlfriend", PartOfSpeech.NOUN),
                            VocabSeed("夫", "おっと", "husband", "husband", PartOfSpeech.NOUN),
                            VocabSeed("妻", "つま", "wife", "wife", PartOfSpeech.NOUN),
                            VocabSeed("結婚", "けっこん", "marriage", "marriage", PartOfSpeech.NOUN),
                            VocabSeed("離婚", "りこん", "divorce", "divorce", PartOfSpeech.NOUN),
                            VocabSeed("付き合う", "つきあう", "date", "to date/go out with", PartOfSpeech.VERB),
                        ),
                    ),
                ),
            ),
            TopicSeed(
                title = "Health & Body",
                description = "Vocabulary about health and body parts.",
                totalDays = 8,
                courses = listOf(
                    CourseSeed(
                        title = "Body Parts",
                        description = "Parts of the body.",
                        vocabularies = listOf(
                            VocabSeed("体", "からだ", "body", "body", PartOfSpeech.NOUN),
                            VocabSeed("頭", "あたま", "head", "head", PartOfSpeech.NOUN),
                            VocabSeed("髪", "かみ", "hair", "hair", PartOfSpeech.NOUN),
                            VocabSeed("目", "め", "eye", "eye", PartOfSpeech.NOUN),
                            VocabSeed("耳", "みみ", "ear", "ear", PartOfSpeech.NOUN),
                            VocabSeed("鼻", "はな", "nose", "nose", PartOfSpeech.NOUN),
                            VocabSeed("口", "くち", "mouth", "mouth", PartOfSpeech.NOUN),
                            VocabSeed("歯", "は", "tooth", "tooth", PartOfSpeech.NOUN),
                            VocabSeed("首", "くび", "neck", "neck", PartOfSpeech.NOUN),
                            VocabSeed("肩", "かた", "shoulder", "shoulder", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "More Body Parts",
                        description = "Additional body parts.",
                        vocabularies = listOf(
                            VocabSeed("腕", "うで", "arm", "arm", PartOfSpeech.NOUN),
                            VocabSeed("手", "て", "hand", "hand", PartOfSpeech.NOUN),
                            VocabSeed("指", "ゆび", "finger", "finger", PartOfSpeech.NOUN),
                            VocabSeed("足", "あし", "leg/foot", "leg/foot", PartOfSpeech.NOUN),
                            VocabSeed("背中", "せなか", "back", "back", PartOfSpeech.NOUN),
                            VocabSeed("お腹", "おなか", "stomach", "stomach", PartOfSpeech.NOUN),
                            VocabSeed("胸", "むね", "chest", "chest", PartOfSpeech.NOUN),
                            VocabSeed("心臓", "しんぞう", "heart", "heart (organ)", PartOfSpeech.NOUN),
                            VocabSeed("血", "ち", "blood", "blood", PartOfSpeech.NOUN),
                            VocabSeed("骨", "ほね", "bone", "bone", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Health & Illness",
                        description = "Health-related vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("病気", "びょうき", "illness", "illness/sick", PartOfSpeech.NOUN),
                            VocabSeed("風邪", "かぜ", "cold", "cold (illness)", PartOfSpeech.NOUN),
                            VocabSeed("熱", "ねつ", "fever", "fever", PartOfSpeech.NOUN),
                            VocabSeed("薬", "くすり", "medicine", "medicine", PartOfSpeech.NOUN),
                            VocabSeed("医者", "いしゃ", "doctor", "doctor", PartOfSpeech.NOUN),
                            VocabSeed("看護師", "かんごし", "nurse", "nurse", PartOfSpeech.NOUN),
                            VocabSeed("痛い", "いたい", "painful", "painful", PartOfSpeech.ADJ),
                            VocabSeed("具合", "ぐあい", "condition", "condition/health", PartOfSpeech.NOUN),
                            VocabSeed("治る", "なおる", "recover", "to recover", PartOfSpeech.VERB),
                            VocabSeed("入院", "にゅういん", "hospitalization", "hospitalization", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Symptoms",
                        description = "Common symptoms.",
                        vocabularies = listOf(
                            VocabSeed("咳", "せき", "cough", "cough", PartOfSpeech.NOUN),
                            VocabSeed("頭痛", "ずつう", "headache", "headache", PartOfSpeech.NOUN),
                            VocabSeed("腹痛", "ふくつう", "stomachache", "stomachache", PartOfSpeech.NOUN),
                            VocabSeed("吐き気", "はきけ", "nausea", "nausea", PartOfSpeech.NOUN),
                            VocabSeed("めまい", "めまい", "dizziness", "dizziness", PartOfSpeech.NOUN),
                            VocabSeed("疲れる", "つかれる", "get tired", "to get tired", PartOfSpeech.VERB),
                            VocabSeed("眠い", "ねむい", "sleepy", "sleepy", PartOfSpeech.ADJ),
                            VocabSeed("だるい", "だるい", "sluggish", "sluggish", PartOfSpeech.ADJ),
                            VocabSeed("怪我", "けが", "injury", "injury", PartOfSpeech.NOUN),
                            VocabSeed("アレルギー", "あれるぎー", "allergy", "allergy", PartOfSpeech.NOUN),
                        ),
                    ),
                ),
            ),
            TopicSeed(
                title = "Weather & Seasons",
                description = "Vocabulary about weather and seasons.",
                totalDays = 6,
                courses = listOf(
                    CourseSeed(
                        title = "Weather",
                        description = "Weather vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("天気", "てんき", "weather", "weather", PartOfSpeech.NOUN),
                            VocabSeed("晴れ", "はれ", "sunny", "sunny/clear", PartOfSpeech.NOUN),
                            VocabSeed("曇り", "くもり", "cloudy", "cloudy", PartOfSpeech.NOUN),
                            VocabSeed("雨", "あめ", "rain", "rain", PartOfSpeech.NOUN),
                            VocabSeed("雪", "ゆき", "snow", "snow", PartOfSpeech.NOUN),
                            VocabSeed("風", "かぜ", "wind", "wind", PartOfSpeech.NOUN),
                            VocabSeed("台風", "たいふう", "typhoon", "typhoon", PartOfSpeech.NOUN),
                            VocabSeed("雷", "かみなり", "thunder", "thunder/lightning", PartOfSpeech.NOUN),
                            VocabSeed("降る", "ふる", "fall", "to fall (rain/snow)", PartOfSpeech.VERB),
                            VocabSeed("傘", "かさ", "umbrella", "umbrella", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Seasons",
                        description = "Seasons and related vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("季節", "きせつ", "season", "season", PartOfSpeech.NOUN),
                            VocabSeed("春", "はる", "spring", "spring", PartOfSpeech.NOUN),
                            VocabSeed("夏", "なつ", "summer", "summer", PartOfSpeech.NOUN),
                            VocabSeed("秋", "あき", "autumn", "autumn/fall", PartOfSpeech.NOUN),
                            VocabSeed("冬", "ふゆ", "winter", "winter", PartOfSpeech.NOUN),
                            VocabSeed("暖かい", "あたたかい", "warm", "warm", PartOfSpeech.ADJ),
                            VocabSeed("涼しい", "すずしい", "cool", "cool", PartOfSpeech.ADJ),
                            VocabSeed("暑い", "あつい", "hot", "hot (weather)", PartOfSpeech.ADJ),
                            VocabSeed("寒い", "さむい", "cold", "cold (weather)", PartOfSpeech.ADJ),
                            VocabSeed("湿度", "しつど", "humidity", "humidity", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Temperature & Climate",
                        description = "Temperature and climate words.",
                        vocabularies = listOf(
                            VocabSeed("気温", "きおん", "temperature", "temperature", PartOfSpeech.NOUN),
                            VocabSeed("度", "ど", "degree", "degree", PartOfSpeech.NOUN),
                            VocabSeed("蒸し暑い", "むしあつい", "humid", "hot and humid", PartOfSpeech.ADJ),
                            VocabSeed("乾燥", "かんそう", "dry", "dry/dryness", PartOfSpeech.NOUN),
                            VocabSeed("予報", "よほう", "forecast", "forecast", PartOfSpeech.NOUN),
                            VocabSeed("晴れる", "はれる", "clear up", "to clear up", PartOfSpeech.VERB),
                            VocabSeed("曇る", "くもる", "get cloudy", "to get cloudy", PartOfSpeech.VERB),
                            VocabSeed("止む", "やむ", "stop", "to stop (rain)", PartOfSpeech.VERB),
                            VocabSeed("霧", "きり", "fog", "fog", PartOfSpeech.NOUN),
                            VocabSeed("虹", "にじ", "rainbow", "rainbow", PartOfSpeech.NOUN),
                        ),
                    ),
                ),
            ),
            TopicSeed(
                title = "Education & Study",
                description = "Vocabulary about education and studying.",
                totalDays = 8,
                courses = listOf(
                    CourseSeed(
                        title = "School",
                        description = "School vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("学校", "がっこう", "school", "school", PartOfSpeech.NOUN),
                            VocabSeed("大学", "だいがく", "university", "university", PartOfSpeech.NOUN),
                            VocabSeed("高校", "こうこう", "high school", "high school", PartOfSpeech.NOUN),
                            VocabSeed("中学校", "ちゅうがっこう", "middle school", "middle school", PartOfSpeech.NOUN),
                            VocabSeed("小学校", "しょうがっこう", "elementary school", "elementary school", PartOfSpeech.NOUN),
                            VocabSeed("教室", "きょうしつ", "classroom", "classroom", PartOfSpeech.NOUN),
                            VocabSeed("図書館", "としょかん", "library", "library", PartOfSpeech.NOUN),
                            VocabSeed("体育館", "たいいくかん", "gymnasium", "gymnasium", PartOfSpeech.NOUN),
                            VocabSeed("校長", "こうちょう", "principal", "principal", PartOfSpeech.NOUN),
                            VocabSeed("クラス", "くらす", "class", "class", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Subjects",
                        description = "School subjects.",
                        vocabularies = listOf(
                            VocabSeed("科目", "かもく", "subject", "subject", PartOfSpeech.NOUN),
                            VocabSeed("数学", "すうがく", "mathematics", "mathematics", PartOfSpeech.NOUN),
                            VocabSeed("英語", "えいご", "English", "English", PartOfSpeech.NOUN),
                            VocabSeed("国語", "こくご", "Japanese", "Japanese (subject)", PartOfSpeech.NOUN),
                            VocabSeed("理科", "りか", "science", "science", PartOfSpeech.NOUN),
                            VocabSeed("社会", "しゃかい", "social studies", "social studies", PartOfSpeech.NOUN),
                            VocabSeed("歴史", "れきし", "history", "history", PartOfSpeech.NOUN),
                            VocabSeed("地理", "ちり", "geography", "geography", PartOfSpeech.NOUN),
                            VocabSeed("音楽", "おんがく", "music", "music", PartOfSpeech.NOUN),
                            VocabSeed("美術", "びじゅつ", "art", "art", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Study Actions",
                        description = "Actions related to studying.",
                        vocabularies = listOf(
                            VocabSeed("勉強", "べんきょう", "study", "study", PartOfSpeech.NOUN),
                            VocabSeed("勉強する", "べんきょうする", "study", "to study", PartOfSpeech.VERB),
                            VocabSeed("習う", "ならう", "learn", "to learn", PartOfSpeech.VERB),
                            VocabSeed("教える", "おしえる", "teach", "to teach", PartOfSpeech.VERB),
                            VocabSeed("覚える", "おぼえる", "memorize", "to memorize", PartOfSpeech.VERB),
                            VocabSeed("忘れる", "わすれる", "forget", "to forget", PartOfSpeech.VERB),
                            VocabSeed("練習", "れんしゅう", "practice", "practice", PartOfSpeech.NOUN),
                            VocabSeed("復習", "ふくしゅう", "review", "review", PartOfSpeech.NOUN),
                            VocabSeed("予習", "よしゅう", "preparation", "preparation (study)", PartOfSpeech.NOUN),
                            VocabSeed("質問", "しつもん", "question", "question", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Exams & Grades",
                        description = "Exams and academic performance.",
                        vocabularies = listOf(
                            VocabSeed("試験", "しけん", "exam", "exam", PartOfSpeech.NOUN),
                            VocabSeed("テスト", "てすと", "test", "test", PartOfSpeech.NOUN),
                            VocabSeed("宿題", "しゅくだい", "homework", "homework", PartOfSpeech.NOUN),
                            VocabSeed("点数", "てんすう", "score", "score", PartOfSpeech.NOUN),
                            VocabSeed("成績", "せいせき", "grades", "grades", PartOfSpeech.NOUN),
                            VocabSeed("合格", "ごうかく", "pass", "to pass (exam)", PartOfSpeech.NOUN),
                            VocabSeed("不合格", "ふごうかく", "fail", "to fail (exam)", PartOfSpeech.NOUN),
                            VocabSeed("卒業", "そつぎょう", "graduation", "graduation", PartOfSpeech.NOUN),
                            VocabSeed("入学", "にゅうがく", "enrollment", "enrollment", PartOfSpeech.NOUN),
                            VocabSeed("答え", "こたえ", "answer", "answer", PartOfSpeech.NOUN),
                        ),
                    ),
                ),
            ),
            TopicSeed(
                title = "Work & Career",
                description = "Vocabulary about work and careers.",
                totalDays = 8,
                courses = listOf(
                    CourseSeed(
                        title = "Occupations",
                        description = "Various occupations.",
                        vocabularies = listOf(
                            VocabSeed("仕事", "しごと", "job", "job/work", PartOfSpeech.NOUN),
                            VocabSeed("会社員", "かいしゃいん", "office worker", "company employee", PartOfSpeech.NOUN),
                            VocabSeed("社長", "しゃちょう", "president", "company president", PartOfSpeech.NOUN),
                            VocabSeed("部長", "ぶちょう", "manager", "department manager", PartOfSpeech.NOUN),
                            VocabSeed("課長", "かちょう", "section chief", "section chief", PartOfSpeech.NOUN),
                            VocabSeed("弁護士", "べんごし", "lawyer", "lawyer", PartOfSpeech.NOUN),
                            VocabSeed("エンジニア", "えんじにあ", "engineer", "engineer", PartOfSpeech.NOUN),
                            VocabSeed("公務員", "こうむいん", "civil servant", "civil servant", PartOfSpeech.NOUN),
                            VocabSeed("警察官", "けいさつかん", "police officer", "police officer", PartOfSpeech.NOUN),
                            VocabSeed("消防士", "しょうぼうし", "firefighter", "firefighter", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Workplace",
                        description = "Workplace vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("会社", "かいしゃ", "company", "company", PartOfSpeech.NOUN),
                            VocabSeed("オフィス", "おふぃす", "office", "office", PartOfSpeech.NOUN),
                            VocabSeed("デスク", "ですく", "desk", "desk", PartOfSpeech.NOUN),
                            VocabSeed("パソコン", "ぱそこん", "computer", "personal computer", PartOfSpeech.NOUN),
                            VocabSeed("コピー機", "こぴーき", "copier", "copy machine", PartOfSpeech.NOUN),
                            VocabSeed("会議室", "かいぎしつ", "meeting room", "conference room", PartOfSpeech.NOUN),
                            VocabSeed("受付", "うけつけ", "reception", "reception", PartOfSpeech.NOUN),
                            VocabSeed("エレベーター", "えれべーたー", "elevator", "elevator", PartOfSpeech.NOUN),
                            VocabSeed("階段", "かいだん", "stairs", "stairs", PartOfSpeech.NOUN),
                            VocabSeed("駐車場", "ちゅうしゃじょう", "parking lot", "parking lot", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Work Actions",
                        description = "Work-related verbs.",
                        vocabularies = listOf(
                            VocabSeed("働く", "はたらく", "work", "to work", PartOfSpeech.VERB),
                            VocabSeed("出勤", "しゅっきん", "go to work", "going to work", PartOfSpeech.NOUN),
                            VocabSeed("退勤", "たいきん", "leave work", "leaving work", PartOfSpeech.NOUN),
                            VocabSeed("残業", "ざんぎょう", "overtime", "overtime work", PartOfSpeech.NOUN),
                            VocabSeed("出張", "しゅっちょう", "business trip", "business trip", PartOfSpeech.NOUN),
                            VocabSeed("休暇", "きゅうか", "vacation", "vacation/leave", PartOfSpeech.NOUN),
                            VocabSeed("給料", "きゅうりょう", "salary", "salary", PartOfSpeech.NOUN),
                            VocabSeed("昇進", "しょうしん", "promotion", "promotion", PartOfSpeech.NOUN),
                            VocabSeed("転職", "てんしょく", "job change", "change jobs", PartOfSpeech.NOUN),
                            VocabSeed("辞める", "やめる", "quit", "to quit", PartOfSpeech.VERB),
                        ),
                    ),
                    CourseSeed(
                        title = "Business Terms",
                        description = "Business-related terms.",
                        vocabularies = listOf(
                            VocabSeed("契約", "けいやく", "contract", "contract", PartOfSpeech.NOUN),
                            VocabSeed("商品", "しょうひん", "product", "product", PartOfSpeech.NOUN),
                            VocabSeed("サービス", "さーびす", "service", "service", PartOfSpeech.NOUN),
                            VocabSeed("顧客", "こきゃく", "customer", "customer", PartOfSpeech.NOUN),
                            VocabSeed("取引先", "とりひきさき", "client", "business partner", PartOfSpeech.NOUN),
                            VocabSeed("売上", "うりあげ", "sales", "sales", PartOfSpeech.NOUN),
                            VocabSeed("利益", "りえき", "profit", "profit", PartOfSpeech.NOUN),
                            VocabSeed("経費", "けいひ", "expenses", "expenses", PartOfSpeech.NOUN),
                            VocabSeed("プロジェクト", "ぷろじぇくと", "project", "project", PartOfSpeech.NOUN),
                            VocabSeed("締め切り", "しめきり", "deadline", "deadline", PartOfSpeech.NOUN),
                        ),
                    ),
                ),
            ),
            TopicSeed(
                title = "Hobbies & Leisure",
                description = "Vocabulary about hobbies and leisure activities.",
                totalDays = 8,
                courses = listOf(
                    CourseSeed(
                        title = "Sports",
                        description = "Sports vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("スポーツ", "すぽーつ", "sports", "sports", PartOfSpeech.NOUN),
                            VocabSeed("サッカー", "さっかー", "soccer", "soccer", PartOfSpeech.NOUN),
                            VocabSeed("野球", "やきゅう", "baseball", "baseball", PartOfSpeech.NOUN),
                            VocabSeed("テニス", "てにす", "tennis", "tennis", PartOfSpeech.NOUN),
                            VocabSeed("バスケ", "ばすけ", "basketball", "basketball", PartOfSpeech.NOUN),
                            VocabSeed("水泳", "すいえい", "swimming", "swimming", PartOfSpeech.NOUN),
                            VocabSeed("ゴルフ", "ごるふ", "golf", "golf", PartOfSpeech.NOUN),
                            VocabSeed("試合", "しあい", "match", "match/game", PartOfSpeech.NOUN),
                            VocabSeed("勝つ", "かつ", "win", "to win", PartOfSpeech.VERB),
                            VocabSeed("負ける", "まける", "lose", "to lose", PartOfSpeech.VERB),
                        ),
                    ),
                    CourseSeed(
                        title = "Entertainment",
                        description = "Entertainment vocabulary.",
                        vocabularies = listOf(
                            VocabSeed("映画", "えいが", "movie", "movie", PartOfSpeech.NOUN),
                            VocabSeed("音楽", "おんがく", "music", "music", PartOfSpeech.NOUN),
                            VocabSeed("ゲーム", "げーむ", "game", "game", PartOfSpeech.NOUN),
                            VocabSeed("漫画", "まんが", "manga", "manga/comic", PartOfSpeech.NOUN),
                            VocabSeed("アニメ", "あにめ", "anime", "anime", PartOfSpeech.NOUN),
                            VocabSeed("ドラマ", "どらま", "drama", "TV drama", PartOfSpeech.NOUN),
                            VocabSeed("コンサート", "こんさーと", "concert", "concert", PartOfSpeech.NOUN),
                            VocabSeed("カラオケ", "からおけ", "karaoke", "karaoke", PartOfSpeech.NOUN),
                            VocabSeed("歌う", "うたう", "sing", "to sing", PartOfSpeech.VERB),
                            VocabSeed("踊る", "おどる", "dance", "to dance", PartOfSpeech.VERB),
                        ),
                    ),
                    CourseSeed(
                        title = "Outdoor Activities",
                        description = "Outdoor activities.",
                        vocabularies = listOf(
                            VocabSeed("旅行", "りょこう", "travel", "travel", PartOfSpeech.NOUN),
                            VocabSeed("キャンプ", "きゃんぷ", "camping", "camping", PartOfSpeech.NOUN),
                            VocabSeed("登山", "とざん", "hiking", "mountain climbing", PartOfSpeech.NOUN),
                            VocabSeed("釣り", "つり", "fishing", "fishing", PartOfSpeech.NOUN),
                            VocabSeed("散歩", "さんぽ", "walk", "walk/stroll", PartOfSpeech.NOUN),
                            VocabSeed("ジョギング", "じょぎんぐ", "jogging", "jogging", PartOfSpeech.NOUN),
                            VocabSeed("サイクリング", "さいくりんぐ", "cycling", "cycling", PartOfSpeech.NOUN),
                            VocabSeed("ピクニック", "ぴくにっく", "picnic", "picnic", PartOfSpeech.NOUN),
                            VocabSeed("バーベキュー", "ばーべきゅー", "barbecue", "barbecue", PartOfSpeech.NOUN),
                            VocabSeed("写真", "しゃしん", "photo", "photo", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Indoor Hobbies",
                        description = "Indoor hobbies.",
                        vocabularies = listOf(
                            VocabSeed("趣味", "しゅみ", "hobby", "hobby", PartOfSpeech.NOUN),
                            VocabSeed("読書", "どくしょ", "reading", "reading", PartOfSpeech.NOUN),
                            VocabSeed("料理", "りょうり", "cooking", "cooking", PartOfSpeech.NOUN),
                            VocabSeed("絵", "え", "drawing", "drawing/picture", PartOfSpeech.NOUN),
                            VocabSeed("書道", "しょどう", "calligraphy", "calligraphy", PartOfSpeech.NOUN),
                            VocabSeed("茶道", "さどう", "tea ceremony", "tea ceremony", PartOfSpeech.NOUN),
                            VocabSeed("園芸", "えんげい", "gardening", "gardening", PartOfSpeech.NOUN),
                            VocabSeed("編み物", "あみもの", "knitting", "knitting", PartOfSpeech.NOUN),
                            VocabSeed("楽器", "がっき", "instrument", "musical instrument", PartOfSpeech.NOUN),
                            VocabSeed("ピアノ", "ぴあの", "piano", "piano", PartOfSpeech.NOUN),
                        ),
                    ),
                ),
            ),
        )

        seedSyllabusContent(n4Syllabus, n4TopicSeeds)

        return n4Syllabus
    }
}
