package com.exe.vocafy_BE.initializer

import com.exe.vocafy_BE.enum.LanguageCode
import com.exe.vocafy_BE.enum.LanguageSet
import com.exe.vocafy_BE.enum.PartOfSpeech
import com.exe.vocafy_BE.enum.SyllabusSourceType
import com.exe.vocafy_BE.enum.SyllabusVisibility
import com.exe.vocafy_BE.model.entity.Syllabus

object JlptN5PublicSeed : SyllabusSeedModule {
    override val key: String = "jlpt-n5-public"

    override fun seed(context: SyllabusSeedContext): Syllabus = with(context) {
        val publicSyllabus = syllabusRepository.save(
            Syllabus(
                title = "JLPT N5 Starter",
                description = "JLPT N5 vocabulary seeded from Vocabulary_of_JLPT_N5.pdf (MLC list, 802 entries).",
                imageBackGroud = "https://jlptsensei.com/jlpt-n5-particles-list/",
                imageIcon = "https://www.vjlink.edu.vn/nhung-dieu-ban-nen-biet-ve-tieng-nhat-n5/",
                totalDays = 120,
                languageSet = LanguageSet.EN_JP_VI,
                studyLanguage = LanguageCode.JA,
                visibility = SyllabusVisibility.PUBLIC,
                sourceType = SyllabusSourceType.CURATED,
                createdBy = owner,
                active = true,
                category = generalCategory
            )
        )

        val topicSeeds = listOf(
            TopicSeed(
                title = "MLC JLPT N5 Vocabulary",
                description = "Structured vocabulary imported from the provided JLPT N5 PDF file.",
                totalDays = 120,
                courses = listOf(
                    CourseSeed(
                        title = "Set 01 (1-40)",
                        description = "Vocabulary items #1 to #40 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("～駅", "～えき", "... station", "... station", PartOfSpeech.NOUN),
                            VocabSeed("～円", "～えん", "... yen", "... yen", PartOfSpeech.NOUN),
                            VocabSeed("～かい", "～かい", "... floor", "... floor", PartOfSpeech.NOUN),
                            VocabSeed("～かい", "～かい", "... times", "... times", PartOfSpeech.NOUN),
                            VocabSeed("～日間", "～かかん", "for", "for ... day(s)", PartOfSpeech.NOUN),
                            VocabSeed("～か月", "～かげつ", "(for)", "(for) ... month(s)", PartOfSpeech.NOUN),
                            VocabSeed("～かた", "～かた", "how to", "how to ...", PartOfSpeech.NOUN),
                            VocabSeed("～月", "～がつ", "... month", "... month", PartOfSpeech.NOUN),
                            VocabSeed("～がります", "～がります", "(third person) wants to", "(third person) wants to ... [「〜たい」のstem]＋[てform of がります]＋ います", PartOfSpeech.VERB),
                            VocabSeed("～がわ", "～がわ", "... side", "... side", PartOfSpeech.NOUN),
                            VocabSeed("～キロ", "～キロ", "... kg =", "... kg =", PartOfSpeech.NOUN),
                            VocabSeed("～キロ", "～キロ", "... km = キロメートル", "... km = キロメートル", PartOfSpeech.NOUN),
                            VocabSeed("～くらい/ぐらい", "～くらい/ぐらい", "about", "about ...", PartOfSpeech.NOUN),
                            VocabSeed("～グラム", "～グラム", "... gram", "... gram", PartOfSpeech.NOUN),
                            VocabSeed("～こ", "～こ", "counter for small object", "counter for small object", PartOfSpeech.NOUN),
                            VocabSeed("～語", "～ご", "... language", "... language", PartOfSpeech.NOUN),
                            VocabSeed("～ごろ", "～ごろ", "around", "around ... (for time)", PartOfSpeech.NOUN),
                            VocabSeed("～さい", "～さい", "... year(s) old", "... year(s) old", PartOfSpeech.NOUN),
                            VocabSeed("～さつ", "～さつ", "counter for book", "counter for book", PartOfSpeech.NOUN),
                            VocabSeed("～さん", "～さん", "Mr", "Mr., Mrs., Miss", PartOfSpeech.NOUN),
                            VocabSeed("～時", "～じ", "... o'clock", "... o'clock", PartOfSpeech.NOUN),
                            VocabSeed("～時間", "～じかん", "... hour(s)", "... hour(s)", PartOfSpeech.NOUN),
                            VocabSeed("～週間", "～しゅうかん", "(for)", "(for) ... week(s)", PartOfSpeech.NOUN),
                            VocabSeed("～人", "～じん", "...an, ...ese", "...an, ...ese", PartOfSpeech.NOUN),
                            VocabSeed("～すぎ", "～すぎ", "past, over", "past, over", PartOfSpeech.NOUN),
                            VocabSeed("～ずつ", "～ずつ", "... each", "... each", PartOfSpeech.NOUN),
                            VocabSeed("～先生", "～せんせい", "teacher", "teacher", PartOfSpeech.NOUN),
                            VocabSeed("～だい", "～だい", "counter for machine", "counter for machine", PartOfSpeech.NOUN),
                            VocabSeed("～たち", "～たち", "...s, ... and others", "...s, ... and others", PartOfSpeech.NOUN),
                            VocabSeed("～中", "～ちゅう", "be in middle of", "be in middle of ..., (during) in ...", PartOfSpeech.NOUN),
                            VocabSeed("～つ", "～つ", "counter for object", "counter for object", PartOfSpeech.NOUN),
                            VocabSeed("～ど", "～ど", "... time(s)", "... time(s)", PartOfSpeech.NOUN),
                            VocabSeed("～日", "～にち", "...st, ...nd, ...th", "...st, ...nd, ...th", PartOfSpeech.NOUN),
                            VocabSeed("～人", "～にん", "counter for person", "counter for person", PartOfSpeech.NOUN),
                            VocabSeed("～年", "～ねん", "... years", "... years", PartOfSpeech.NOUN),
                            VocabSeed("～はい/ばい/ぱい", "～はい/ばい/ぱい", "cups of", "cups of ...", PartOfSpeech.NOUN),
                            VocabSeed("～半", "～はん", "half", "half", PartOfSpeech.NOUN),
                            VocabSeed("～ばん", "～ばん", "No", "No. ...", PartOfSpeech.NOUN),
                            VocabSeed("～ひき/びき/ぴき", "～ひき/びき/ぴき", "counter for animal", "counter for animal", PartOfSpeech.NOUN),
                            VocabSeed("～分", "～ふん/ぷん", "... minute(s)", "... minute(s)", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 02 (41-80)",
                        description = "Vocabulary items #41 to #80 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("～ページ", "～ページ", "... page", "... page", PartOfSpeech.NOUN),
                            VocabSeed("～本", "～ほん/ぼん/ぽん", "counter for long object", "counter for long object", PartOfSpeech.NOUN),
                            VocabSeed("～まい", "～まい", "counter for thin object", "counter for thin object", PartOfSpeech.NOUN),
                            VocabSeed("～前", "～まえ", "2ねん前に にほんに きました。I came to Japan two years ago", "2ねん前に にほんに きました。I came to Japan two years ago.", PartOfSpeech.NOUN),
                            VocabSeed("～メートル", "～メートル", "... meter", "... meter", PartOfSpeech.NOUN),
                            VocabSeed("～や", "～や", "... store, ... shop", "... store, ... shop", PartOfSpeech.NOUN),
                            VocabSeed("会います", "あいます", "see (a person), meet", "see (a person), meet", PartOfSpeech.VERB),
                            VocabSeed("あおい", "あおい", "blue [i-adj", "blue [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("赤", "あか", "red [noun]", "red [noun]", PartOfSpeech.NOUN),
                            VocabSeed("赤い", "あかい", "red [i-adj", "red [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あがります", "あがります", "go up", "go up", PartOfSpeech.VERB),
                            VocabSeed("あかるい", "あかるい", "bright, light [i-adj", "bright, light [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あき", "あき", "autumn, fall", "autumn, fall", PartOfSpeech.NOUN),
                            VocabSeed("あきます", "あきます", "open", "open", PartOfSpeech.VERB),
                            VocabSeed("あけます", "あけます", "open", "open", PartOfSpeech.VERB),
                            VocabSeed("あげます", "あげます", "give", "give", PartOfSpeech.VERB),
                            VocabSeed("朝", "あさ", "morning", "morning", PartOfSpeech.NOUN),
                            VocabSeed("朝ごはん", "あさごはん", "breakfast", "breakfast", PartOfSpeech.NOUN),
                            VocabSeed("あさって", "あさって", "the day after tomorrow", "the day after tomorrow", PartOfSpeech.NOUN),
                            VocabSeed("足", "あし", "leg, foot", "leg, foot", PartOfSpeech.NOUN),
                            VocabSeed("あした", "あした", "tomorrow", "tomorrow", PartOfSpeech.NOUN),
                            VocabSeed("あそこ", "あそこ", "over there", "over there", PartOfSpeech.NOUN),
                            VocabSeed("あそびます", "あそびます", "play", "play", PartOfSpeech.VERB),
                            VocabSeed("あたたかい", "あたたかい", "warm [i-adj", "warm [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あたま", "あたま", "head", "head", PartOfSpeech.NOUN),
                            VocabSeed("新しい", "あたらしい", "new [i-adj", "new [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あちら", "あちら", "over there 「あそこ」の more polite", "over there 「あそこ」の more polite", PartOfSpeech.NOUN),
                            VocabSeed("あつい", "あつい", "hot [i-adj", "hot [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あつい", "あつい", "thick [i-adj", "thick [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("後(で)", "あと(で)", "after", "after", PartOfSpeech.NOUN),
                            VocabSeed("あに", "あに", "(my) older brother", "(my) older brother", PartOfSpeech.NOUN),
                            VocabSeed("あね", "あね", "(my) older sister", "(my) older sister", PartOfSpeech.NOUN),
                            VocabSeed("あの～", "あの～", "that", "that ...", PartOfSpeech.NOUN),
                            VocabSeed("アパート", "アパート", "apartment", "apartment", PartOfSpeech.NOUN),
                            VocabSeed("あびます", "あびます", "take (a shower)", "take (a shower)", PartOfSpeech.VERB),
                            VocabSeed("あぶない", "あぶない", "dangerous [i-adj", "dangerous [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あまい", "あまい", "sweet [i-adj", "sweet [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あまり", "あまり", "not much", "not much ...", PartOfSpeech.NOUN),
                            VocabSeed("雨", "あめ", "rain", "rain", PartOfSpeech.NOUN),
                            VocabSeed("アメリカ", "アメリカ", "The United States of America", "The United States of America", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 03 (81-120)",
                        description = "Vocabulary items #81 to #120 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("あらいます", "あらいます", "wash", "wash", PartOfSpeech.VERB),
                            VocabSeed("あります", "あります", "be [existence]", "be [existence]", PartOfSpeech.VERB),
                            VocabSeed("あります", "あります", "have [possession]", "have [possession]", PartOfSpeech.VERB),
                            VocabSeed("歩きます", "あるきます", "walk", "walk", PartOfSpeech.VERB),
                            VocabSeed("あれ", "あれ", "that (one)", "that (one)", PartOfSpeech.NOUN),
                            VocabSeed("いい", "いい", "good [i-adj", "good [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("言います", "いいます", "say, tell", "say, tell", PartOfSpeech.VERB),
                            VocabSeed("家", "いえ", "house", "house", PartOfSpeech.NOUN),
                            VocabSeed("行きます", "いきます", "go", "go", PartOfSpeech.VERB),
                            VocabSeed("いくつ", "いくつ", "how many, how old", "how many, how old", PartOfSpeech.NOUN),
                            VocabSeed("いくら", "いくら", "how much", "how much", PartOfSpeech.NOUN),
                            VocabSeed("いけ", "いけ", "pond", "pond", PartOfSpeech.NOUN),
                            VocabSeed("いしゃ", "いしゃ", "doctor = おいしゃさん。", "doctor = おいしゃさん。", PartOfSpeech.NOUN),
                            VocabSeed("いす", "いす", "chair", "chair", PartOfSpeech.NOUN),
                            VocabSeed("いそがしい", "いそがしい", "busy [i-adj", "busy [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("いたい", "いたい", "be painful [i-adj", "be painful [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("一", "いち", "one", "one", PartOfSpeech.NOUN),
                            VocabSeed("一ど", "いちど", "once", "once", PartOfSpeech.NOUN),
                            VocabSeed("一日", "いちにち", "one day", "one day", PartOfSpeech.NOUN),
                            VocabSeed("一ばん", "いちばん", "the best", "the best", PartOfSpeech.NOUN),
                            VocabSeed("いつ", "いつ", "when", "when", PartOfSpeech.NOUN),
                            VocabSeed("五日", "いつか", "the fifth day of the month, five days", "the fifth day of the month, five days", PartOfSpeech.NOUN),
                            VocabSeed("いっしょ(に)", "いっしょ(に)", "together", "together", PartOfSpeech.NOUN),
                            VocabSeed("五つ", "いつつ", "five", "five", PartOfSpeech.NOUN),
                            VocabSeed("いつも", "いつも", "always", "always", PartOfSpeech.NOUN),
                            VocabSeed("今", "いま", "now", "now", PartOfSpeech.NOUN),
                            VocabSeed("います", "います", "いま いえに います。I'm at home now", "いま いえに います。I'm at home now.", PartOfSpeech.VERB),
                            VocabSeed("いみ", "いみ", "meaning", "meaning", PartOfSpeech.NOUN),
                            VocabSeed("いもうと", "いもうと", "(my) younger sister", "(my) younger sister", PartOfSpeech.NOUN),
                            VocabSeed("いもうとさん", "いもうとさん", "(someone's) younger sister", "(someone's) younger sister", PartOfSpeech.NOUN),
                            VocabSeed("いや", "いや", "hateful, not likable, unpleasant [na-adj", "hateful, not likable, unpleasant [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("入口", "いりぐち", "entrance", "entrance", PartOfSpeech.NOUN),
                            VocabSeed("いります", "いります", "be necessary, must have, need", "be necessary, must have, need", PartOfSpeech.VERB),
                            VocabSeed("入れます", "いれます", "put in", "put in", PartOfSpeech.VERB),
                            VocabSeed("いろ", "いろ", "color", "color", PartOfSpeech.NOUN),
                            VocabSeed("いろいろ", "いろいろ", "various [na-adj", "various [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("上", "うえ", "on, above, top", "on, above, top", PartOfSpeech.NOUN),
                            VocabSeed("後ろ", "うしろ", "back, behind", "back, behind", PartOfSpeech.NOUN),
                            VocabSeed("うすい", "うすい", "thin [i-adj", "thin [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("うた", "うた", "song", "song", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 04 (121-160)",
                        description = "Vocabulary items #121 to #160 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("うたいます", "うたいます", "sing", "sing", PartOfSpeech.VERB),
                            VocabSeed("うち", "うち", "home", "home", PartOfSpeech.NOUN),
                            VocabSeed("生まれます", "うまれます", "be born", "be born", PartOfSpeech.VERB),
                            VocabSeed("うみ", "うみ", "sea", "sea", PartOfSpeech.NOUN),
                            VocabSeed("うります", "うります", "sell", "sell", PartOfSpeech.VERB),
                            VocabSeed("うるさい", "うるさい", "loud [i-adj", "loud [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("うれしい", "うれしい", "happy, pleased [i-adj", "happy, pleased [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("うわぎ", "うわぎ", "coat, jacket, outerwear", "coat, jacket, outerwear", PartOfSpeech.NOUN),
                            VocabSeed("え", "え", "drawing, picture, painting", "drawing, picture, painting", PartOfSpeech.NOUN),
                            VocabSeed("エアコン", "エアコン", "air conditioner", "air conditioner", PartOfSpeech.NOUN),
                            VocabSeed("えいが", "えいが", "movie", "movie", PartOfSpeech.NOUN),
                            VocabSeed("えいがかん", "えいがかん", "movie theater", "movie theater", PartOfSpeech.NOUN),
                            VocabSeed("えいご", "えいご", "English", "English", PartOfSpeech.NOUN),
                            VocabSeed("駅", "えき", "station", "station", PartOfSpeech.NOUN),
                            VocabSeed("えらびます", "えらびます", "choose", "choose", PartOfSpeech.VERB),
                            VocabSeed("エレベーター", "エレベーター", "elevator, lift", "elevator, lift", PartOfSpeech.NOUN),
                            VocabSeed("えんぴつ", "えんぴつ", "pencil", "pencil", PartOfSpeech.NOUN),
                            VocabSeed("お～", "お～", "[polite prefix]", "[polite prefix]", PartOfSpeech.NOUN),
                            VocabSeed("おいしい", "おいしい", "delicious, good, tasty [i-adj", "delicious, good, tasty [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("おいでになります", "おいでになります", "come, go, be [respect]", "come, go, be [respect]", PartOfSpeech.VERB),
                            VocabSeed("多い", "おおい", "a lot of [i-adj", "a lot of [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("大きい", "おおきい", "big [i-adj", "big [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("大きな", "おおきな", "big 大きな[noun] = 大きい[noun]", "big 大きな[noun] = 大きい[noun]", PartOfSpeech.NOUN),
                            VocabSeed("おおぜい", "おおぜい", "many (people), a great number of (people)", "many (people), a great number of (people)", PartOfSpeech.NOUN),
                            VocabSeed("お母さん", "おかあさん", "(someone's) mother", "(someone's) mother", PartOfSpeech.NOUN),
                            VocabSeed("おかし", "おかし", "confectionery, cake, candy, sweets", "confectionery, cake, candy, sweets", PartOfSpeech.NOUN),
                            VocabSeed("お金", "おかね", "money", "money", PartOfSpeech.NOUN),
                            VocabSeed("おきます", "おきます", "put (Group 1 verb)", "put (Group 1 verb)", PartOfSpeech.VERB),
                            VocabSeed("おきます", "おきます", "get up (Group 2 verb)", "get up (Group 2 verb)", PartOfSpeech.VERB),
                            VocabSeed("おくさん", "おくさん", "(someone's) wife", "(someone's) wife", PartOfSpeech.NOUN),
                            VocabSeed("お国", "おくに", "country = くに。", "country = くに。", PartOfSpeech.NOUN),
                            VocabSeed("おくります", "おくります", "send", "send", PartOfSpeech.VERB),
                            VocabSeed("おさけ", "おさけ", "liquor, (alcoholic) drink, sake", "liquor, (alcoholic) drink, sake", PartOfSpeech.NOUN),
                            VocabSeed("おさら", "おさら", "plate = さら。", "plate = さら。", PartOfSpeech.NOUN),
                            VocabSeed("おじさん", "おじさん", "uncle", "uncle", PartOfSpeech.NOUN),
                            VocabSeed("おじいさん", "おじいさん", "grandfather", "grandfather", PartOfSpeech.NOUN),
                            VocabSeed("おしえます", "おしえます", "teach, tell", "teach, tell", PartOfSpeech.VERB),
                            VocabSeed("おそい", "おそい", "late [i-adj", "late [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("おそく", "おそく", "late [noun]", "late [noun]", PartOfSpeech.NOUN),
                            VocabSeed("おちゃ", "おちゃ", "tea", "tea", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 05 (161-200)",
                        description = "Vocabulary items #161 to #200 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("おてあらい", "おてあらい", "lavatory, toilet", "lavatory, toilet", PartOfSpeech.NOUN),
                            VocabSeed("お父さん", "おとうさん", "(someone's) father", "(someone's) father", PartOfSpeech.NOUN),
                            VocabSeed("おとうと", "おとうと", "(my) younger brother", "(my) younger brother", PartOfSpeech.NOUN),
                            VocabSeed("おとうとさん", "おとうとさん", "(someone's) younger brother", "(someone's) younger brother", PartOfSpeech.NOUN),
                            VocabSeed("男", "おとこ", "male", "male", PartOfSpeech.NOUN),
                            VocabSeed("男の子", "おとこのこ", "boy", "boy", PartOfSpeech.NOUN),
                            VocabSeed("おととい", "おととい", "the day before yesterday", "the day before yesterday", PartOfSpeech.NOUN),
                            VocabSeed("おととし", "おととし", "the year before last", "the year before last", PartOfSpeech.NOUN),
                            VocabSeed("大人", "おとな", "adult", "adult", PartOfSpeech.NOUN),
                            VocabSeed("おなか", "おなか", "stomach", "stomach", PartOfSpeech.NOUN),
                            VocabSeed("おなじ", "おなじ", "same", "same", PartOfSpeech.NOUN),
                            VocabSeed("おにいさん", "おにいさん", "(someone's) older brother", "(someone's) older brother", PartOfSpeech.NOUN),
                            VocabSeed("おにぎり", "おにぎり", "rice ball", "rice ball", PartOfSpeech.NOUN),
                            VocabSeed("おねえさん", "おねえさん", "(someone's) older sister", "(someone's) older sister", PartOfSpeech.NOUN),
                            VocabSeed("おばさん", "おばさん", "aunt", "aunt", PartOfSpeech.NOUN),
                            VocabSeed("おばあさん", "おばあさん", "grandmother", "grandmother", PartOfSpeech.NOUN),
                            VocabSeed("おべんとう", "おべんとう", "lunch box", "lunch box", PartOfSpeech.NOUN),
                            VocabSeed("おぼえます", "おぼえます", "memorize", "memorize", PartOfSpeech.VERB),
                            VocabSeed("お店", "おみせ", "shop = みせ。", "shop = みせ。", PartOfSpeech.NOUN),
                            VocabSeed("おもい", "おもい", "heavy [i-adj", "heavy [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("おもしろい", "おもしろい", "fun, funny, interesting [i-adj", "fun, funny, interesting [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("およぎます", "およぎます", "swim", "swim", PartOfSpeech.VERB),
                            VocabSeed("おります", "おります", "get off", "get off", PartOfSpeech.VERB),
                            VocabSeed("おわります", "おわります", "end, finish", "end, finish", PartOfSpeech.VERB),
                            VocabSeed("おんがく", "おんがく", "music", "music", PartOfSpeech.NOUN),
                            VocabSeed("女", "おんな", "female", "female", PartOfSpeech.NOUN),
                            VocabSeed("女の子", "おんなのこ", "girl", "girl", PartOfSpeech.NOUN),
                            VocabSeed("火", "か", "Tuesday = かようび。", "Tuesday = かようび。", PartOfSpeech.NOUN),
                            VocabSeed("外国", "がいこく", "foreign country", "foreign country", PartOfSpeech.NOUN),
                            VocabSeed("外国人", "がいこくじん", "foreigner", "foreigner", PartOfSpeech.NOUN),
                            VocabSeed("会社", "かいしゃ", "company", "company", PartOfSpeech.NOUN),
                            VocabSeed("かいだん", "かいだん", "stairs", "stairs", PartOfSpeech.NOUN),
                            VocabSeed("かいとうようし", "かいとうようし", "answer sheet", "answer sheet", PartOfSpeech.NOUN),
                            VocabSeed("買います", "かいます", "buy", "buy", PartOfSpeech.VERB),
                            VocabSeed("買いもの", "かいもの", "shopping", "shopping", PartOfSpeech.NOUN),
                            VocabSeed("かえします", "かえします", "return (object)", "return (object)", PartOfSpeech.VERB),
                            VocabSeed("かえります", "かえります", "return, go back", "return, go back", PartOfSpeech.VERB),
                            VocabSeed("かお", "かお", "face", "face", PartOfSpeech.NOUN),
                            VocabSeed("かかります", "かかります", "take (time, money)", "take (time, money)", PartOfSpeech.VERB),
                            VocabSeed("かぎ", "かぎ", "key", "key", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 06 (201-240)",
                        description = "Vocabulary items #201 to #240 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("書きます", "かきます", "write", "write", PartOfSpeech.VERB),
                            VocabSeed("学生", "がくせい", "student", "student", PartOfSpeech.NOUN),
                            VocabSeed("かけます", "かけます", "wear", "wear", PartOfSpeech.VERB),
                            VocabSeed("かけます", "かけます", "call", "call", PartOfSpeech.VERB),
                            VocabSeed("かさ", "かさ", "umbrella", "umbrella", PartOfSpeech.NOUN),
                            VocabSeed("かします", "かします", "lend", "lend", PartOfSpeech.VERB),
                            VocabSeed("かぜ", "かぜ", "wind", "wind", PartOfSpeech.NOUN),
                            VocabSeed("かぜ", "かぜ", "cold", "cold", PartOfSpeech.NOUN),
                            VocabSeed("かぞく", "かぞく", "family", "family", PartOfSpeech.NOUN),
                            VocabSeed("かた", "かた", "person (respect)", "person (respect)", PartOfSpeech.NOUN),
                            VocabSeed("カタカナ", "カタカナ", "katakana", "katakana", PartOfSpeech.NOUN),
                            VocabSeed("学校", "がっこう", "school", "school", PartOfSpeech.NOUN),
                            VocabSeed("かど", "かど", "corner", "corner", PartOfSpeech.NOUN),
                            VocabSeed("かない", "かない", "(my) wife", "(my) wife", PartOfSpeech.NOUN),
                            VocabSeed("かばん", "かばん", "bag", "bag", PartOfSpeech.NOUN),
                            VocabSeed("かびん", "かびん", "vase", "vase", PartOfSpeech.NOUN),
                            VocabSeed("かぶります", "かぶります", "put on", "put on", PartOfSpeech.VERB),
                            VocabSeed("紙", "かみ", "paper", "paper", PartOfSpeech.NOUN),
                            VocabSeed("カメラ", "カメラ", "camera", "camera", PartOfSpeech.NOUN),
                            VocabSeed("火よう日", "かようび", "Tuesday", "Tuesday", PartOfSpeech.NOUN),
                            VocabSeed("からい", "からい", "hot, spicy [i-adj", "hot, spicy [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("からだ", "からだ", "body", "body", PartOfSpeech.NOUN),
                            VocabSeed("かります", "かります", "borrow", "borrow", PartOfSpeech.VERB),
                            VocabSeed("かるい", "かるい", "light, not heavy [i-adj", "light, not heavy [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("カレンダー", "カレンダー", "calendar", "calendar", PartOfSpeech.NOUN),
                            VocabSeed("川", "かわ", "river", "river", PartOfSpeech.NOUN),
                            VocabSeed("かわいい", "かわいい", "pretty, sweet, cute [i-adj", "pretty, sweet, cute [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("かんがえます", "かんがえます", "consider, think", "consider, think", PartOfSpeech.VERB),
                            VocabSeed("かんじ", "かんじ", "kanji", "kanji", PartOfSpeech.NOUN),
                            VocabSeed("かんたん", "かんたん", "easy [na-adj", "easy [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("木", "き", "tree", "tree", PartOfSpeech.NOUN),
                            VocabSeed("きいろい", "きいろい", "yellow [i-adj", "yellow [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("きえます", "きえます", "go out, go off", "go out, go off", PartOfSpeech.VERB),
                            VocabSeed("聞きます", "ききます", "ask, hear, listen", "ask, hear, listen", PartOfSpeech.VERB),
                            VocabSeed("北", "きた", "north", "north", PartOfSpeech.NOUN),
                            VocabSeed("ギター", "ギター", "guitar", "guitar", PartOfSpeech.NOUN),
                            VocabSeed("きたない", "きたない", "dirty [i-adj", "dirty [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("きっさてん", "きっさてん", "coffee shop", "coffee shop", PartOfSpeech.NOUN),
                            VocabSeed("きって", "きって", "stamp", "stamp", PartOfSpeech.NOUN),
                            VocabSeed("きっぷ", "きっぷ", "ticket", "ticket", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 07 (241-280)",
                        description = "Vocabulary items #241 to #280 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("きのう", "きのう", "yesterday", "yesterday", PartOfSpeech.NOUN),
                            VocabSeed("来ます", "きます", "come", "come", PartOfSpeech.VERB),
                            VocabSeed("きます", "きます", "put on, wear", "put on, wear", PartOfSpeech.VERB),
                            VocabSeed("九", "きゅう", "nine", "nine", PartOfSpeech.NOUN),
                            VocabSeed("ぎゅうにく", "ぎゅうにく", "beef", "beef", PartOfSpeech.NOUN),
                            VocabSeed("ぎゅうにゅう", "ぎゅうにゅう", "milk", "milk", PartOfSpeech.NOUN),
                            VocabSeed("今日", "きょう", "today", "today", PartOfSpeech.NOUN),
                            VocabSeed("きょうしつ", "きょうしつ", "classroom", "classroom", PartOfSpeech.NOUN),
                            VocabSeed("きょうだい", "きょうだい", "brothers and sisters", "brothers and sisters; siblings", PartOfSpeech.NOUN),
                            VocabSeed("きょうと", "きょうと", "Kyoto [name of city]", "Kyoto [name of city]", PartOfSpeech.NOUN),
                            VocabSeed("きょねん", "きょねん", "last year", "last year", PartOfSpeech.NOUN),
                            VocabSeed("きらい", "きらい", "hateful, unpleasant, not likable [na-adj", "hateful, unpleasant, not likable [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("きります", "きります", "cut", "cut", PartOfSpeech.VERB),
                            VocabSeed("きれい", "きれい", "beautiful, clean [na-adj", "beautiful, clean [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("金", "きん", "Friday = きんようび。", "Friday = きんようび。", PartOfSpeech.NOUN),
                            VocabSeed("銀行", "ぎんこう", "bank", "bank", PartOfSpeech.NOUN),
                            VocabSeed("金よう日", "きんようび", "Friday", "Friday", PartOfSpeech.NOUN),
                            VocabSeed("九", "く", "nine", "nine", PartOfSpeech.NOUN),
                            VocabSeed("くすり", "くすり", "medicine", "medicine", PartOfSpeech.NOUN),
                            VocabSeed("くだもの", "くだもの", "fruit", "fruit", PartOfSpeech.NOUN),
                            VocabSeed("口", "くち", "mouth", "mouth", PartOfSpeech.NOUN),
                            VocabSeed("くつ", "くつ", "shoes", "shoes", PartOfSpeech.NOUN),
                            VocabSeed("くつ下", "くつした", "socks", "socks", PartOfSpeech.NOUN),
                            VocabSeed("国", "くに", "country", "country", PartOfSpeech.NOUN),
                            VocabSeed("くもり", "くもり", "cloudy weather", "cloudy weather", PartOfSpeech.NOUN),
                            VocabSeed("くらい", "くらい", "dark [i-adj", "dark [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("クラス", "クラス", "class", "class", PartOfSpeech.NOUN),
                            VocabSeed("車", "くるま", "car", "car", PartOfSpeech.NOUN),
                            VocabSeed("くろ", "くろ", "black [noun]", "black [noun]", PartOfSpeech.NOUN),
                            VocabSeed("くろい", "くろい", "black [i-adj", "black [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("くろく", "くろく", "black [adv", "black [adv.]", PartOfSpeech.ADV),
                            VocabSeed("ケーキ", "ケーキ", "cake", "cake", PartOfSpeech.NOUN),
                            VocabSeed("今朝", "けさ", "this morning", "this morning", PartOfSpeech.NOUN),
                            VocabSeed("けしゴム", "けしゴム", "eraser", "eraser", PartOfSpeech.NOUN),
                            VocabSeed("けします", "けします", "switch off, turn off, erase", "switch off, turn off, erase", PartOfSpeech.VERB),
                            VocabSeed("月", "げつ", "Monday = げつようび。", "Monday = げつようび。", PartOfSpeech.NOUN),
                            VocabSeed("けっこんします", "けっこんします", "get married", "get married", PartOfSpeech.VERB),
                            VocabSeed("月よう日", "げつようび", "Monday", "Monday", PartOfSpeech.NOUN),
                            VocabSeed("げんかん", "げんかん", "front door, front entrance", "front door, front entrance", PartOfSpeech.NOUN),
                            VocabSeed("げんき", "げんき", "fine [na-adj", "fine [na-adj.]", PartOfSpeech.ADJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 08 (281-320)",
                        description = "Vocabulary items #281 to #320 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("五", "ご", "five", "five", PartOfSpeech.NOUN),
                            VocabSeed("こうえん", "こうえん", "park", "park", PartOfSpeech.NOUN),
                            VocabSeed("こうばん", "こうばん", "police box", "police box", PartOfSpeech.NOUN),
                            VocabSeed("こえ", "こえ", "voice", "voice", PartOfSpeech.NOUN),
                            VocabSeed("コート", "コート", "coat", "coat", PartOfSpeech.NOUN),
                            VocabSeed("コーヒー", "コーヒー", "coffee", "coffee", PartOfSpeech.NOUN),
                            VocabSeed("ここ", "ここ", "here", "here", PartOfSpeech.NOUN),
                            VocabSeed("午後", "ごご", "afternoon, p", "afternoon, p.m.", PartOfSpeech.NOUN),
                            VocabSeed("九日", "ここのか", "ninth day of the month, nine days", "ninth day of the month, nine days", PartOfSpeech.NOUN),
                            VocabSeed("九つ", "ここのつ", "nine", "nine", PartOfSpeech.NOUN),
                            VocabSeed("ごしゅじん", "ごしゅじん", "(someone's) husband", "(someone's) husband", PartOfSpeech.NOUN),
                            VocabSeed("午前", "ごぜん", "a", "a.m.", PartOfSpeech.NOUN),
                            VocabSeed("こたえ", "こたえ", "answer", "answer", PartOfSpeech.NOUN),
                            VocabSeed("こたえかた", "こたえかた", "how to answer", "how to answer", PartOfSpeech.NOUN),
                            VocabSeed("こたえます", "こたえます", "answer", "answer", PartOfSpeech.VERB),
                            VocabSeed("こちら", "こちら", "this side, this place, this one", "this side, this place, this one", PartOfSpeech.NOUN),
                            VocabSeed("コップ", "コップ", "glass, drinking cup", "glass, drinking cup", PartOfSpeech.NOUN),
                            VocabSeed("今年", "ことし", "this year", "this year", PartOfSpeech.NOUN),
                            VocabSeed("ことば", "ことば", "word, language, phrase", "word, language, phrase", PartOfSpeech.NOUN),
                            VocabSeed("子ども", "こども", "child", "child", PartOfSpeech.NOUN),
                            VocabSeed("この～", "この～", "this", "this ...", PartOfSpeech.NOUN),
                            VocabSeed("ごはん", "ごはん", "rice, meal", "rice, meal", PartOfSpeech.NOUN),
                            VocabSeed("コピー", "コピー", "copy", "copy", PartOfSpeech.NOUN),
                            VocabSeed("コピーします", "コピーします", "make a copy", "make a copy", PartOfSpeech.VERB),
                            VocabSeed("こまります", "こまります", "be in trouble", "be in trouble", PartOfSpeech.VERB),
                            VocabSeed("これ", "これ", "this (one)", "this (one)", PartOfSpeech.NOUN),
                            VocabSeed("words", "words", "from the old \"Japanese Language Proficiency Test Level 4\") and 46 greetings word", "from the old \"Japanese Language Proficiency Test Level 4\") and 46 greetings words for JLPT N5.", PartOfSpeech.NOUN),
                            VocabSeed("今週", "こんしゅう", "this week", "this week", PartOfSpeech.NOUN),
                            VocabSeed("こんな", "こんな", "this sort of, like this [na-adj", "this sort of, like this [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("こんばん", "こんばん", "tonight", "tonight", PartOfSpeech.NOUN),
                            VocabSeed("さいご", "さいご", "end, last time", "end, last time", PartOfSpeech.NOUN),
                            VocabSeed("魚", "さかな", "fish", "fish", PartOfSpeech.NOUN),
                            VocabSeed("先", "さき", "former, earlier", "former, earlier", PartOfSpeech.NOUN),
                            VocabSeed("さきます", "さきます", "bloom", "bloom", PartOfSpeech.VERB),
                            VocabSeed("さくぶん", "さくぶん", "composition", "composition", PartOfSpeech.NOUN),
                            VocabSeed("さします", "さします", "put up (umbrella)", "put up (umbrella)", PartOfSpeech.VERB),
                            VocabSeed("サッカー", "サッカー", "soccer, football", "soccer, football", PartOfSpeech.NOUN),
                            VocabSeed("ざっし", "ざっし", "magazine", "magazine", PartOfSpeech.NOUN),
                            VocabSeed("さとう", "さとう", "sugar", "sugar", PartOfSpeech.NOUN),
                            VocabSeed("さむい", "さむい", "cold (weather) [i-adj", "cold (weather) [i-adj.]", PartOfSpeech.ADJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 09 (321-360)",
                        description = "Vocabulary items #321 to #360 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("さらいねん", "さらいねん", "the year after next", "the year after next", PartOfSpeech.NOUN),
                            VocabSeed("三", "さん", "three", "three", PartOfSpeech.NOUN),
                            VocabSeed("さんぽ", "さんぽ", "walk", "walk", PartOfSpeech.NOUN),
                            VocabSeed("さんぽ(を)します", "さんぽ(を)します", "take a walk", "take a walk", PartOfSpeech.VERB),
                            VocabSeed("四", "し", "four = よん。", "four = よん。", PartOfSpeech.NOUN),
                            VocabSeed("しお", "しお", "salt", "salt", PartOfSpeech.NOUN),
                            VocabSeed("しかし", "しかし", "but, however (formal, written language)", "but, however (formal, written language)", PartOfSpeech.NOUN),
                            VocabSeed("時間", "じかん", "time", "time", PartOfSpeech.NOUN),
                            VocabSeed("しごと", "しごと", "work", "work", PartOfSpeech.NOUN),
                            VocabSeed("じしょ", "じしょ", "dictionary", "dictionary", PartOfSpeech.NOUN),
                            VocabSeed("しずか", "しずか", "quiet [na-adj", "quiet [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("下", "した", "under, below", "under, below", PartOfSpeech.NOUN),
                            VocabSeed("しつもん", "しつもん", "question", "question", PartOfSpeech.NOUN),
                            VocabSeed("じてんしゃ", "じてんしゃ", "bicycle", "bicycle", PartOfSpeech.NOUN),
                            VocabSeed("じどうしゃ", "じどうしゃ", "car", "car", PartOfSpeech.NOUN),
                            VocabSeed("しにます", "しにます", "die", "die", PartOfSpeech.VERB),
                            VocabSeed("じびき", "じびき", "dictionary = じしょ", "dictionary = じしょ", PartOfSpeech.NOUN),
                            VocabSeed("じぶん", "じぶん", "oneself", "oneself", PartOfSpeech.NOUN),
                            VocabSeed("します", "します", "do", "do", PartOfSpeech.VERB),
                            VocabSeed("しまります", "しまります", "close (intransitive verb)", "close (intransitive verb)", PartOfSpeech.VERB),
                            VocabSeed("しめます", "しめます", "close (transitive verb)", "close (transitive verb)", PartOfSpeech.VERB),
                            VocabSeed("しゃしん", "しゃしん", "photograph, photo, picture", "photograph, photo, picture", PartOfSpeech.NOUN),
                            VocabSeed("シャツ", "シャツ", "shirt", "shirt", PartOfSpeech.NOUN),
                            VocabSeed("シャワー", "シャワー", "shower", "shower", PartOfSpeech.NOUN),
                            VocabSeed("週", "しゅう", "week", "week", PartOfSpeech.NOUN),
                            VocabSeed("十", "じゅう", "ten", "ten", PartOfSpeech.NOUN),
                            VocabSeed("ジュース", "ジュース", "juice", "juice", PartOfSpeech.NOUN),
                            VocabSeed("じゅぎょう", "じゅぎょう", "class, lesson", "class, lesson", PartOfSpeech.NOUN),
                            VocabSeed("しゅくだい", "しゅくだい", "homework", "homework", PartOfSpeech.NOUN),
                            VocabSeed("上手", "じょうず", "good, skillful [na-adj", "good, skillful [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("上手に", "じょうずに", "well [adv", "well [adv.]", PartOfSpeech.ADV),
                            VocabSeed("じょうぶ", "じょうぶ", "healthy, strong, firm, durable [na-adj", "healthy, strong, firm, durable [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("しょうゆ", "しょうゆ", "soy sauce", "soy sauce", PartOfSpeech.NOUN),
                            VocabSeed("しょくどう", "しょくどう", "dining room", "dining room", PartOfSpeech.NOUN),
                            VocabSeed("知ります", "しります", "know", "know", PartOfSpeech.VERB),
                            VocabSeed("白い", "しろい", "white [i-adj", "white [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("新聞", "しんぶん", "newspaper", "newspaper", PartOfSpeech.NOUN),
                            VocabSeed("水", "すい", "Wednesday = すいようび。", "Wednesday = すいようび。", PartOfSpeech.NOUN),
                            VocabSeed("すいます", "すいます", "breath in, smoke", "breath in, smoke", PartOfSpeech.VERB),
                            VocabSeed("水よう日", "すいようび", "Wednesday", "Wednesday", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 10 (361-400)",
                        description = "Vocabulary items #361 to #400 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("スカート", "スカート", "skirt", "skirt", PartOfSpeech.NOUN),
                            VocabSeed("すき", "すき", "like [na-adj", "like [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("少ない", "すくない", "few", "few", PartOfSpeech.NOUN),
                            VocabSeed("すぐに", "すぐに", "soon, right away", "soon, right away", PartOfSpeech.NOUN),
                            VocabSeed("少し", "すこし", "a little", "a little", PartOfSpeech.NOUN),
                            VocabSeed("すし", "すし", "sushi", "sushi", PartOfSpeech.NOUN),
                            VocabSeed("すしや", "すしや", "sushi restaurant", "sushi restaurant", PartOfSpeech.NOUN),
                            VocabSeed("すずしい", "すずしい", "cool (weather) [i-adj", "cool (weather) [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ストーブ", "ストーブ", "stove, heater", "stove, heater", PartOfSpeech.NOUN),
                            VocabSeed("スプーン", "スプーン", "spoon", "spoon", PartOfSpeech.NOUN),
                            VocabSeed("スポーツ", "スポーツ", "sports", "sports", PartOfSpeech.NOUN),
                            VocabSeed("ズボン", "ズボン", "trousers, pants", "trousers, pants", PartOfSpeech.NOUN),
                            VocabSeed("住みます", "すみます", "live, inhabit", "live, inhabit", PartOfSpeech.VERB),
                            VocabSeed("スリッパ", "スリッパ", "slippers", "slippers", PartOfSpeech.NOUN),
                            VocabSeed("すわります", "すわります", "sit down", "sit down", PartOfSpeech.VERB),
                            VocabSeed("せ", "せ", "height", "height", PartOfSpeech.NOUN),
                            VocabSeed("せいと", "せいと", "student", "student", PartOfSpeech.NOUN),
                            VocabSeed("セーター", "セーター", "sweater", "sweater", PartOfSpeech.NOUN),
                            VocabSeed("せっけん", "せっけん", "soap", "soap", PartOfSpeech.NOUN),
                            VocabSeed("せびろ", "せびろ", "jacket, suit", "jacket, suit", PartOfSpeech.NOUN),
                            VocabSeed("せまい", "せまい", "narrow, not spacious [i-adj", "narrow, not spacious [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ゼロ", "ゼロ", "zero", "zero", PartOfSpeech.NOUN),
                            VocabSeed("千", "せん", "thousand", "thousand", PartOfSpeech.NOUN),
                            VocabSeed("先月", "せんげつ", "last month", "last month", PartOfSpeech.NOUN),
                            VocabSeed("先週", "せんしゅう", "last week", "last week", PartOfSpeech.NOUN),
                            VocabSeed("先生", "せんせい", "teacher", "teacher", PartOfSpeech.NOUN),
                            VocabSeed("せんたく", "せんたく", "washing, laundry", "washing, laundry", PartOfSpeech.NOUN),
                            VocabSeed("ぜんぶ", "ぜんぶ", "all", "all", PartOfSpeech.NOUN),
                            VocabSeed("そうじ", "そうじ", "cleaning", "cleaning", PartOfSpeech.NOUN),
                            VocabSeed("そうじします", "そうじします", "clean", "clean", PartOfSpeech.VERB),
                            VocabSeed("そこ", "そこ", "there", "there", PartOfSpeech.NOUN),
                            VocabSeed("そして", "そして", "and, then", "and, then", PartOfSpeech.NOUN),
                            VocabSeed("そちら", "そちら", "there, your place", "there, your place", PartOfSpeech.NOUN),
                            VocabSeed("外", "そと", "outside", "outside", PartOfSpeech.NOUN),
                            VocabSeed("その～", "その～", "that", "that ...", PartOfSpeech.NOUN),
                            VocabSeed("そば", "そば", "nearby", "nearby", PartOfSpeech.NOUN),
                            VocabSeed("空", "そら", "sky", "sky", PartOfSpeech.NOUN),
                            VocabSeed("それ", "それ", "that (one)", "that (one)", PartOfSpeech.NOUN),
                            VocabSeed("それから", "それから", "and then, after that", "and then, after that", PartOfSpeech.NOUN),
                            VocabSeed("それでは", "それでは", "then, well", "then, well", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 11 (401-440)",
                        description = "Vocabulary items #401 to #440 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("大学", "だいがく", "university", "university", PartOfSpeech.NOUN),
                            VocabSeed("たいしかん", "たいしかん", "embassy", "embassy", PartOfSpeech.NOUN),
                            VocabSeed("だいじょうぶ", "だいじょうぶ", "okay, no problem [na-adj", "okay, no problem [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("だいすき", "だいすき", "be very fond of, like very much [na-adj", "be very fond of, like very much [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("たいせつ", "たいせつ", "important [na-adj", "important [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("だいたい", "だいたい", "almost", "almost", PartOfSpeech.NOUN),
                            VocabSeed("たいてい", "たいてい", "mostly, usually", "mostly, usually", PartOfSpeech.NOUN),
                            VocabSeed("だいどころ", "だいどころ", "kitchen", "kitchen", PartOfSpeech.NOUN),
                            VocabSeed("たいへん", "たいへん", "very [adv", "very [adv.] (formal)", PartOfSpeech.ADV),
                            VocabSeed("たいへん", "たいへん", "serious, hard, difficult [na-adj", "serious, hard, difficult [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("高い", "たかい", "expensive [i-adj", "expensive [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("高い", "たかい", "tall, high [i-adj", "tall, high [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("だから", "だから", "so, therefore", "so, therefore", PartOfSpeech.NOUN),
                            VocabSeed("たくさん", "たくさん", "many, much", "many, much", PartOfSpeech.NOUN),
                            VocabSeed("タクシー", "タクシー", "taxi", "taxi", PartOfSpeech.NOUN),
                            VocabSeed("出します", "だします", "take out", "take out", PartOfSpeech.VERB),
                            VocabSeed("ただしい", "ただしい", "correct [i-adj", "correct [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("立ちます", "たちます", "stand up", "stand up", PartOfSpeech.VERB),
                            VocabSeed("たてもの", "たてもの", "building", "building", PartOfSpeech.NOUN),
                            VocabSeed("たのしい", "たのしい", "enjoyable, pleasant [i-adj", "enjoyable, pleasant [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("たのみます", "たのみます", "ask, request", "ask, request", PartOfSpeech.VERB),
                            VocabSeed("たばこ", "たばこ", "cigarette, tobacco", "cigarette, tobacco", PartOfSpeech.NOUN),
                            VocabSeed("たぶん", "たぶん", "probably, perhaps", "probably, perhaps", PartOfSpeech.NOUN),
                            VocabSeed("食べもの", "たべもの", "food", "food", PartOfSpeech.NOUN),
                            VocabSeed("食べます", "たべます", "eat", "eat", PartOfSpeech.VERB),
                            VocabSeed("たまご", "たまご", "egg", "egg", PartOfSpeech.NOUN),
                            VocabSeed("だれ", "だれ", "who", "who", PartOfSpeech.NOUN),
                            VocabSeed("たんじょうび", "たんじょうび", "birthday", "birthday", PartOfSpeech.NOUN),
                            VocabSeed("だんだん", "だんだん", "gradually, little by little", "gradually, little by little", PartOfSpeech.NOUN),
                            VocabSeed("小さい", "ちいさい", "small", "small", PartOfSpeech.NOUN),
                            VocabSeed("小さな", "ちいさな+[noun]", "small 小さな+[noun]", "small 小さな+[noun]", PartOfSpeech.NOUN),
                            VocabSeed("近い", "ちかい", "near, close [i-adj", "near, close [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ちがいます", "ちがいます", "be different, differ", "be different, differ", PartOfSpeech.VERB),
                            VocabSeed("近く", "ちかく", "neighborhood [noun]", "neighborhood [noun]", PartOfSpeech.NOUN),
                            VocabSeed("ちかてつ", "ちかてつ", "subway", "subway", PartOfSpeech.NOUN),
                            VocabSeed("ちず", "ちず", "map", "map", PartOfSpeech.NOUN),
                            VocabSeed("父", "ちち", "(my) father", "(my) father", PartOfSpeech.NOUN),
                            VocabSeed("ちゃいろ", "ちゃいろ", "brown", "brown", PartOfSpeech.NOUN),
                            VocabSeed("ちゃわん", "ちゃわん", "(rice) bowl", "(rice) bowl", PartOfSpeech.NOUN),
                            VocabSeed("ちょうど", "ちょうど", "just", "just", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 12 (441-480)",
                        description = "Vocabulary items #441 to #480 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("ちょっと", "ちょっと", "a little", "a little", PartOfSpeech.NOUN),
                            VocabSeed("一日", "ついたち", "the first day of the month", "the first day of the month", PartOfSpeech.NOUN),
                            VocabSeed("つかいます", "つかいます", "use", "use", PartOfSpeech.VERB),
                            VocabSeed("つかれます", "つかれます", "get tired", "get tired", PartOfSpeech.VERB),
                            VocabSeed("つぎ", "つぎ", "next", "next", PartOfSpeech.NOUN),
                            VocabSeed("つきます", "つきます", "arrive", "arrive", PartOfSpeech.VERB),
                            VocabSeed("つくえ", "つくえ", "desk", "desk", PartOfSpeech.NOUN),
                            VocabSeed("つくりかた", "つくりかた", "how to make", "how to make", PartOfSpeech.NOUN),
                            VocabSeed("つくります", "つくります", "make", "make", PartOfSpeech.VERB),
                            VocabSeed("つけます", "つけます", "turn on", "turn on", PartOfSpeech.VERB),
                            VocabSeed("つとめます", "つとめます", "work for", "work for", PartOfSpeech.VERB),
                            VocabSeed("つまらない", "つまらない", "uninteresting, boring [i-adj", "uninteresting, boring [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("つめたい", "つめたい", "cold (object) [i-adj", "cold (object) [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("つよい", "つよい", "strong [i-adj", "strong [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("手", "て", "hand", "hand", PartOfSpeech.NOUN),
                            VocabSeed("ティッシュペーパー", "ティッシュペーパー", "tissue", "tissue", PartOfSpeech.NOUN),
                            VocabSeed("テープ", "テープ", "tape", "tape", PartOfSpeech.NOUN),
                            VocabSeed("テープレコーダー", "テープレコーダー", "tape recorder", "tape recorder", PartOfSpeech.NOUN),
                            VocabSeed("テーブル", "テーブル", "table", "table", PartOfSpeech.NOUN),
                            VocabSeed("出かけます", "でかけます", "go out", "go out", PartOfSpeech.VERB),
                            VocabSeed("手紙", "てがみ", "letter", "letter", PartOfSpeech.NOUN),
                            VocabSeed("できます", "できます", "can", "can", PartOfSpeech.VERB),
                            VocabSeed("出口", "でぐち", "exit", "exit", PartOfSpeech.NOUN),
                            VocabSeed("テスト", "テスト", "test", "test", PartOfSpeech.NOUN),
                            VocabSeed("では", "では", "then, well then = じゃ。", "then, well then = じゃ。", PartOfSpeech.NOUN),
                            VocabSeed("デパート", "デパート", "department store", "department store", PartOfSpeech.NOUN),
                            VocabSeed("出ます", "でます", "leave", "leave", PartOfSpeech.VERB),
                            VocabSeed("でも", "でも", "but", "but", PartOfSpeech.NOUN),
                            VocabSeed("テレビ", "テレビ", "TV", "TV", PartOfSpeech.NOUN),
                            VocabSeed("天気", "てんき", "weather", "weather", PartOfSpeech.NOUN),
                            VocabSeed("電気", "でんき", "electricity", "electricity", PartOfSpeech.NOUN),
                            VocabSeed("電車", "でんしゃ", "train", "train", PartOfSpeech.NOUN),
                            VocabSeed("電話", "でんわ", "telephone", "telephone", PartOfSpeech.NOUN),
                            VocabSeed("電話します", "でんわします", "call, ring", "call, ring", PartOfSpeech.VERB),
                            VocabSeed("電話ばんごう", "でんわばんごう", "telephone number", "telephone number", PartOfSpeech.NOUN),
                            VocabSeed("と", "と", "door", "door", PartOfSpeech.NOUN),
                            VocabSeed("ど", "ど", "Saturday = どようび。", "Saturday = どようび。", PartOfSpeech.NOUN),
                            VocabSeed("ドア", "ドア", "door", "door", PartOfSpeech.NOUN),
                            VocabSeed("トイレ", "トイレ", "toilet, lavatory", "toilet, lavatory", PartOfSpeech.NOUN),
                            VocabSeed("トイレットペーパー", "トイレットペーパー", "toilet paper", "toilet paper", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 13 (481-520)",
                        description = "Vocabulary items #481 to #520 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("どう", "どう", "how", "how", PartOfSpeech.NOUN),
                            VocabSeed("とうきょう", "とうきょう", "Tokyo", "Tokyo", PartOfSpeech.NOUN),
                            VocabSeed("どうして", "どうして", "why", "why", PartOfSpeech.NOUN),
                            VocabSeed("とうふ", "とうふ", "tofu", "tofu", PartOfSpeech.NOUN),
                            VocabSeed("どうぶつ", "どうぶつ", "animal", "animal", PartOfSpeech.NOUN),
                            VocabSeed("十", "とお", "ten", "ten", PartOfSpeech.NOUN),
                            VocabSeed("とおい", "とおい", "far [i-adj", "far [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("とおく", "とおく", "distantly, far [noun]", "distantly, far [noun]", PartOfSpeech.NOUN),
                            VocabSeed("十日", "とおか", "the tenth day of the month, ten days", "the tenth day of the month, ten days", PartOfSpeech.NOUN),
                            VocabSeed("ときどき", "ときどき", "sometimes", "sometimes", PartOfSpeech.NOUN),
                            VocabSeed("とけい", "とけい", "clock, watch", "clock, watch", PartOfSpeech.NOUN),
                            VocabSeed("どこ", "どこ", "where", "where", PartOfSpeech.NOUN),
                            VocabSeed("どこか", "どこか", "somewhere", "somewhere", PartOfSpeech.NOUN),
                            VocabSeed("ところ", "ところ", "place", "place", PartOfSpeech.NOUN),
                            VocabSeed("としょかん", "としょかん", "library", "library", PartOfSpeech.NOUN),
                            VocabSeed("どちら", "どちら", "いいですか。Which would you like, coffee or tea?", "いいですか。Which would you like, coffee or tea?", PartOfSpeech.NOUN),
                            VocabSeed("とても", "とても", "very", "very", PartOfSpeech.NOUN),
                            VocabSeed("どなた", "どなた", "のpolite", "のpolite", PartOfSpeech.NOUN),
                            VocabSeed("となり", "となり", "next to", "next to", PartOfSpeech.NOUN),
                            VocabSeed("どの～", "どの～", "which", "which ...", PartOfSpeech.NOUN),
                            VocabSeed("とびます", "とびます", "fly", "fly", PartOfSpeech.VERB),
                            VocabSeed("とまります", "とまります", "stop", "stop", PartOfSpeech.VERB),
                            VocabSeed("友だち", "ともだち", "friend", "friend", PartOfSpeech.NOUN),
                            VocabSeed("土よう日", "どようび", "Saturday", "Saturday", PartOfSpeech.NOUN),
                            VocabSeed("とり", "とり", "bird", "bird", PartOfSpeech.NOUN),
                            VocabSeed("とりにく", "とりにく", "chicken", "chicken", PartOfSpeech.NOUN),
                            VocabSeed("とります", "とります", "take", "take", PartOfSpeech.VERB),
                            VocabSeed("とります", "とります", "take (photographs)", "take (photographs)", PartOfSpeech.VERB),
                            VocabSeed("どれ", "どれ", "which one", "which one", PartOfSpeech.NOUN),
                            VocabSeed("どんな", "どんな", "what kind of", "what kind of ...", PartOfSpeech.NOUN),
                            VocabSeed("ナイフ", "ナイフ", "knife", "knife", PartOfSpeech.NOUN),
                            VocabSeed("中", "なか", "inside", "inside", PartOfSpeech.NOUN),
                            VocabSeed("長い", "ながい", "long [i-adj", "long [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("なきます", "なきます", "sing, mew, moo, etc", "sing, mew, moo, etc.", PartOfSpeech.VERB),
                            VocabSeed("なつ", "なつ", "summer", "summer", PartOfSpeech.NOUN),
                            VocabSeed("など", "など", "and so on, etc", "and so on, etc.", PartOfSpeech.NOUN),
                            VocabSeed("七つ", "ななつ", "seven", "seven", PartOfSpeech.NOUN),
                            VocabSeed("何", "なに", "what", "what", PartOfSpeech.NOUN),
                            VocabSeed("何か", "なにか", "something", "something", PartOfSpeech.NOUN),
                            VocabSeed("七日", "なのか", "the seventh day of the month", "the seventh day of the month", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 14 (521-560)",
                        description = "Vocabulary items #521 to #560 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("名前", "なまえ", "name", "name", PartOfSpeech.NOUN),
                            VocabSeed("ならいます", "ならいます", "learn (from somebody)", "learn (from somebody)", PartOfSpeech.VERB),
                            VocabSeed("ならびます", "ならびます", "(someone) line up", "(someone) line up", PartOfSpeech.VERB),
                            VocabSeed("ならべます", "ならべます", "line up (something)", "line up (something)", PartOfSpeech.VERB),
                            VocabSeed("なります", "なります", "become", "become", PartOfSpeech.VERB),
                            VocabSeed("何", "なん", "what", "what", PartOfSpeech.NOUN),
                            VocabSeed("何時", "なんじ", "what time", "what time", PartOfSpeech.NOUN),
                            VocabSeed("何日", "なんにち", "which day of the month", "which day of the month", PartOfSpeech.NOUN),
                            VocabSeed("二", "に", "two", "two", PartOfSpeech.NOUN),
                            VocabSeed("にぎやか", "にぎやか", "lively [na-adj", "lively [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("にく", "にく", "meat", "meat", PartOfSpeech.NOUN),
                            VocabSeed("西", "にし", "west", "west", PartOfSpeech.NOUN),
                            VocabSeed("日", "にち", "Sunday = にちようび。", "Sunday = にちようび。", PartOfSpeech.NOUN),
                            VocabSeed("日よう日", "にちようび", "Sunday", "Sunday", PartOfSpeech.NOUN),
                            VocabSeed("二年", "にねん", "two years", "two years", PartOfSpeech.NOUN),
                            VocabSeed("日本", "にほん", "Japan", "Japan", PartOfSpeech.NOUN),
                            VocabSeed("日本語", "にほんご", "Japanese language", "Japanese language", PartOfSpeech.NOUN),
                            VocabSeed("にもつ", "にもつ", "baggage", "baggage", PartOfSpeech.NOUN),
                            VocabSeed("ニュース", "ニュース", "news", "news", PartOfSpeech.NOUN),
                            VocabSeed("にわ", "にわ", "garden", "garden", PartOfSpeech.NOUN),
                            VocabSeed("ぬぎます", "ぬぎます", "take off", "take off", PartOfSpeech.VERB),
                            VocabSeed("ぬります", "ぬります", "paint", "paint", PartOfSpeech.VERB),
                            VocabSeed("ネクタイ", "ネクタイ", "necktie", "necktie", PartOfSpeech.NOUN),
                            VocabSeed("ねます", "ねます", "go to bed, sleep", "go to bed, sleep", PartOfSpeech.VERB),
                            VocabSeed("ノート", "ノート", "notebook", "notebook", PartOfSpeech.NOUN),
                            VocabSeed("のぼります", "のぼります", "go up, climb", "go up, climb", PartOfSpeech.VERB),
                            VocabSeed("飲みます", "のみます", "drink", "drink", PartOfSpeech.VERB),
                            VocabSeed("飲みもの", "のみもの", "drinks", "drinks", PartOfSpeech.NOUN),
                            VocabSeed("のります", "のります", "get on, ride, take", "get on, ride, take", PartOfSpeech.VERB),
                            VocabSeed("は", "は", "teeth", "teeth", PartOfSpeech.NOUN),
                            VocabSeed("パーティー", "パーティー", "party", "party", PartOfSpeech.NOUN),
                            VocabSeed("はいざら", "はいざら", "ashtray", "ashtray", PartOfSpeech.NOUN),
                            VocabSeed("入ります", "はいります", "enter", "enter", PartOfSpeech.VERB),
                            VocabSeed("はがき", "はがき", "postcard", "postcard", PartOfSpeech.NOUN),
                            VocabSeed("はきます", "はきます", "put on", "put on", PartOfSpeech.VERB),
                            VocabSeed("はこ", "はこ", "box", "box", PartOfSpeech.NOUN),
                            VocabSeed("はし/おはし", "はし/おはし", "chopsticks", "chopsticks", PartOfSpeech.NOUN),
                            VocabSeed("はし", "はし", "bridge", "bridge", PartOfSpeech.NOUN),
                            VocabSeed("はじまります", "はじまります", "begin, start", "begin, start", PartOfSpeech.VERB),
                            VocabSeed("はじめに", "はじめに", "at the beginning", "at the beginning", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 15 (561-600)",
                        description = "Vocabulary items #561 to #600 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("はじめて", "はじめて", "for the first time", "for the first time", PartOfSpeech.NOUN),
                            VocabSeed("バス", "バス", "bus", "bus", PartOfSpeech.NOUN),
                            VocabSeed("バス会社", "バスがいしゃ", "bus agency, bus company", "bus agency, bus company", PartOfSpeech.NOUN),
                            VocabSeed("バスてい", "バスてい", "bus stop", "bus stop", PartOfSpeech.NOUN),
                            VocabSeed("バスりょこう", "バスりょこう", "bus tour, bus trip", "bus tour, bus trip", PartOfSpeech.NOUN),
                            VocabSeed("バター", "バター", "butter", "butter", PartOfSpeech.NOUN),
                            VocabSeed("はたち", "はたち", "twenty years old", "twenty years old", PartOfSpeech.NOUN),
                            VocabSeed("はたらきます", "はたらきます", "work", "work", PartOfSpeech.VERB),
                            VocabSeed("八", "はち", "eight", "eight", PartOfSpeech.NOUN),
                            VocabSeed("二十日", "はつか", "the twentieth day of the month, twenty days", "the twentieth day of the month, twenty days", PartOfSpeech.NOUN),
                            VocabSeed("はな", "はな", "nose", "nose", PartOfSpeech.NOUN),
                            VocabSeed("花", "はな", "flower", "flower", PartOfSpeech.NOUN),
                            VocabSeed("話", "はなし", "story", "story", PartOfSpeech.NOUN),
                            VocabSeed("話します", "はなします", "speak, talk, tell", "speak, talk, tell", PartOfSpeech.VERB),
                            VocabSeed("母", "はは", "(my) mother", "(my) mother", PartOfSpeech.NOUN),
                            VocabSeed("はやい", "はやい", "early [i-adj", "early [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("はやい", "はやい", "quick, fast [i-adj", "quick, fast [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("はる", "はる", "spring", "spring", PartOfSpeech.NOUN),
                            VocabSeed("はります", "はります", "stick, put something on", "stick, put something on", PartOfSpeech.VERB),
                            VocabSeed("はれ", "はれ", "fair weather", "fair weather", PartOfSpeech.NOUN),
                            VocabSeed("はれます", "はれます", "clear up", "clear up", PartOfSpeech.VERB),
                            VocabSeed("ばん", "ばん", "evening, night", "evening, night", PartOfSpeech.NOUN),
                            VocabSeed("パン", "パン", "bread", "bread", PartOfSpeech.NOUN),
                            VocabSeed("ハンカチ", "ハンカチ", "handkerchief", "handkerchief", PartOfSpeech.NOUN),
                            VocabSeed("ばんごう", "ばんごう", "number", "number", PartOfSpeech.NOUN),
                            VocabSeed("ばんごはん", "ばんごはん", "dinner", "dinner", PartOfSpeech.NOUN),
                            VocabSeed("半分", "はんぶん", "half", "half", PartOfSpeech.NOUN),
                            VocabSeed("パンや", "パンや", "bakery", "bakery", PartOfSpeech.NOUN),
                            VocabSeed("日", "ひ", "day", "day", PartOfSpeech.NOUN),
                            VocabSeed("東", "ひがし", "east", "east", PartOfSpeech.NOUN),
                            VocabSeed("ひきます", "ひきます", "pull", "pull", PartOfSpeech.VERB),
                            VocabSeed("ひきます", "ひきます", "play (music instrument)", "play (music instrument)", PartOfSpeech.VERB),
                            VocabSeed("ひくい", "ひくい", "low [i-adj", "low [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ひこうき", "ひこうき", "airplane", "airplane", PartOfSpeech.NOUN),
                            VocabSeed("左", "ひだり", "left", "left", PartOfSpeech.NOUN),
                            VocabSeed("人", "ひと", "human, person", "human, person", PartOfSpeech.NOUN),
                            VocabSeed("一つ", "ひとつ", "one", "one", PartOfSpeech.NOUN),
                            VocabSeed("一月", "ひとつき", "one month = いっかげつ。", "one month = いっかげつ。", PartOfSpeech.NOUN),
                            VocabSeed("一人", "ひとり", "one person", "one person", PartOfSpeech.NOUN),
                            VocabSeed("ひま", "ひま", "free (time), not busy, spare time [na-adj", "free (time), not busy, spare time [na-adj.]", PartOfSpeech.ADJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 16 (601-640)",
                        description = "Vocabulary items #601 to #640 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("百", "ひゃく", "hundred", "hundred", PartOfSpeech.NOUN),
                            VocabSeed("びょういん", "びょういん", "hospital", "hospital", PartOfSpeech.NOUN),
                            VocabSeed("びょうき", "びょうき", "illness, disease", "illness, disease", PartOfSpeech.NOUN),
                            VocabSeed("ひらがな", "ひらがな", "Hiragana", "Hiragana", PartOfSpeech.NOUN),
                            VocabSeed("昼", "ひる", "daytime, noon", "daytime, noon", PartOfSpeech.NOUN),
                            VocabSeed("ビル", "ビル", "building", "building", PartOfSpeech.NOUN),
                            VocabSeed("昼ごはん", "ひるごはん", "lunch", "lunch", PartOfSpeech.NOUN),
                            VocabSeed("広い", "ひろい", "spacious, wide [i-adj", "spacious, wide [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("フィルム", "フィルム", "film", "film", PartOfSpeech.NOUN),
                            VocabSeed("ふうとう", "ふうとう", "envelope", "envelope", PartOfSpeech.NOUN),
                            VocabSeed("プール", "プール", "swimming pool", "swimming pool", PartOfSpeech.NOUN),
                            VocabSeed("フォーク", "フォーク", "fork", "fork", PartOfSpeech.NOUN),
                            VocabSeed("ふきます", "ふきます", "blow", "blow", PartOfSpeech.VERB),
                            VocabSeed("ふく", "ふく", "clothes", "clothes", PartOfSpeech.NOUN),
                            VocabSeed("二つ", "ふたつ", "two", "two", PartOfSpeech.NOUN),
                            VocabSeed("ぶたにく", "ぶたにく", "pork", "pork", PartOfSpeech.NOUN),
                            VocabSeed("二人", "ふたり", "two people", "two people", PartOfSpeech.NOUN),
                            VocabSeed("二日", "ふつか", "the second day of the month, two days", "the second day of the month, two days", PartOfSpeech.NOUN),
                            VocabSeed("ふとい", "ふとい", "thick, fat [i-adj", "thick, fat [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ふゆ", "ふゆ", "winter", "winter", PartOfSpeech.NOUN),
                            VocabSeed("ふります", "ふります", "fall, come down", "fall, come down", PartOfSpeech.VERB),
                            VocabSeed("古い", "ふるい", "old [i-adj", "old [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ふろ", "ふろ", "bath 「おふろ」more polite", "bath 「おふろ」more polite", PartOfSpeech.NOUN),
                            VocabSeed("文", "ぶん", "sentence", "sentence", PartOfSpeech.NOUN),
                            VocabSeed("つぎの", "ぶんしょう", "text", "text", PartOfSpeech.NOUN),
                            VocabSeed("ページ", "ページ", "page", "page", PartOfSpeech.NOUN),
                            VocabSeed("へた", "へた", "poor, unskillful [na-adj", "poor, unskillful [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ベッド", "ベッド", "bed", "bed", PartOfSpeech.NOUN),
                            VocabSeed("へや", "へや", "room", "room", PartOfSpeech.NOUN),
                            VocabSeed("へん", "へん", "side, part このへん。 = near here", "side, part このへん。 = near here", PartOfSpeech.NOUN),
                            VocabSeed("ペン", "ペン", "pen", "pen", PartOfSpeech.NOUN),
                            VocabSeed("べんきょうします", "べんきょうします", "study", "study", PartOfSpeech.VERB),
                            VocabSeed("べんり", "べんり", "convenience [na-adj", "convenience [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ほう", "ほう", "is", "is ... than A.", PartOfSpeech.NOUN),
                            VocabSeed("ぼうし", "ぼうし", "hat, cap", "hat, cap", PartOfSpeech.NOUN),
                            VocabSeed("ボールペン", "ボールペン", "ballpoint pen", "ballpoint pen", PartOfSpeech.NOUN),
                            VocabSeed("ほか", "ほか", "another, other", "another, other", PartOfSpeech.NOUN),
                            VocabSeed("ぼく", "ぼく", "I (generally young boys, but some adult use as a style)", "I (generally young boys, but some adult use as a style)", PartOfSpeech.NOUN),
                            VocabSeed("ポケット", "ポケット", "pocket", "pocket", PartOfSpeech.NOUN),
                            VocabSeed("ほしい", "ほしい", "want (something) [i-adj", "want (something) [i-adj.]", PartOfSpeech.ADJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 17 (641-680)",
                        description = "Vocabulary items #641 to #680 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("ほそい", "ほそい", "thin, fine [i-adj", "thin, fine [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ボタン", "ボタン", "button", "button", PartOfSpeech.NOUN),
                            VocabSeed("ホテル", "ホテル", "hotel", "hotel", PartOfSpeech.NOUN),
                            VocabSeed("本", "ほん", "book", "book", PartOfSpeech.NOUN),
                            VocabSeed("ほんだな", "ほんだな", "bookshelf", "bookshelf", PartOfSpeech.NOUN),
                            VocabSeed("ほんとう", "ほんとう", "really, truth", "really, truth", PartOfSpeech.NOUN),
                            VocabSeed("ほんや", "ほんや", "bookshop", "bookshop", PartOfSpeech.NOUN),
                            VocabSeed("毎朝", "まいあさ", "every morning", "every morning", PartOfSpeech.NOUN),
                            VocabSeed("毎月", "まいげつ/まいつき", "every month", "every month", PartOfSpeech.NOUN),
                            VocabSeed("毎週", "まいしゅう", "every week", "every week", PartOfSpeech.NOUN),
                            VocabSeed("毎日", "まいにち", "every day", "every day", PartOfSpeech.NOUN),
                            VocabSeed("毎年", "まいねん/まいとし", "every year", "every year", PartOfSpeech.NOUN),
                            VocabSeed("毎ばん", "まいばん", "every night", "every night", PartOfSpeech.NOUN),
                            VocabSeed("前", "まえ", "駅の前の コンビニで かいました。I bought it at a convenience store in front of the station", "駅の前の コンビニで かいました。I bought it at a convenience store in front of the station.", PartOfSpeech.NOUN),
                            VocabSeed("まがります", "まがります", "turn", "turn", PartOfSpeech.VERB),
                            VocabSeed("まずい", "まずい", "nasty, bad-tasting", "nasty, bad-tasting", PartOfSpeech.NOUN),
                            VocabSeed("また", "また", "again", "again", PartOfSpeech.NOUN),
                            VocabSeed("まだ", "まだ", "still, yet", "still, yet", PartOfSpeech.NOUN),
                            VocabSeed("まち", "まち", "town", "town", PartOfSpeech.NOUN),
                            VocabSeed("まちます", "まちます", "wait", "wait", PartOfSpeech.VERB),
                            VocabSeed("まっすぐ", "まっすぐ", "straight [na-adj", "straight [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("マッチ", "マッチ", "match", "match", PartOfSpeech.NOUN),
                            VocabSeed("まど", "まど", "window", "window", PartOfSpeech.NOUN),
                            VocabSeed("まるい", "まるい", "round [i-adj", "round [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("万", "まん", "ten thousand", "ten thousand", PartOfSpeech.NOUN),
                            VocabSeed("まんねんひつ", "まんねんひつ", "fountain pen", "fountain pen", PartOfSpeech.NOUN),
                            VocabSeed("みがきます", "みがきます", "polish, brush", "polish, brush", PartOfSpeech.VERB),
                            VocabSeed("右", "みぎ", "right", "right", PartOfSpeech.NOUN),
                            VocabSeed("みじかい", "みじかい", "short [i-adj", "short [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("水", "みず", "water", "water", PartOfSpeech.NOUN),
                            VocabSeed("店", "みせ", "store", "store", PartOfSpeech.NOUN),
                            VocabSeed("見せます", "みせます", "show", "show", PartOfSpeech.VERB),
                            VocabSeed("道", "みち", "way", "way", PartOfSpeech.NOUN),
                            VocabSeed("三日", "みっか", "the third day of month, three days", "the third day of month, three days", PartOfSpeech.NOUN),
                            VocabSeed("三つ", "みっつ", "three", "three", PartOfSpeech.NOUN),
                            VocabSeed("みなさん", "みなさん", "everyone", "everyone", PartOfSpeech.NOUN),
                            VocabSeed("南", "みなみ", "south", "south", PartOfSpeech.NOUN),
                            VocabSeed("見ます", "みます", "look, see, watch", "look, see, watch", PartOfSpeech.VERB),
                            VocabSeed("耳", "みみ", "ear", "ear", PartOfSpeech.NOUN),
                            VocabSeed("みんな", "みんな", "everyone, everything", "everyone, everything", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 18 (681-720)",
                        description = "Vocabulary items #681 to #720 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("六日", "むいか", "the sixth day of the month", "the sixth day of the month", PartOfSpeech.NOUN),
                            VocabSeed("むこう", "むこう", "over there", "over there", PartOfSpeech.NOUN),
                            VocabSeed("むずかしい", "むずかしい", "difficult [i-adj", "difficult [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("六つ", "むっつ", "six", "six", PartOfSpeech.NOUN),
                            VocabSeed("目", "め", "eye", "eye", PartOfSpeech.NOUN),
                            VocabSeed("メートル", "メートル", "meter", "meter", PartOfSpeech.NOUN),
                            VocabSeed("めがね", "めがね", "glasses", "glasses", PartOfSpeech.NOUN),
                            VocabSeed("メモ", "メモ", "memo", "memo", PartOfSpeech.NOUN),
                            VocabSeed("メモします", "メモします", "make a note", "make a note", PartOfSpeech.VERB),
                            VocabSeed("もう", "もう", "already, yet", "already, yet", PartOfSpeech.NOUN),
                            VocabSeed("もう～", "もう～", "... more", "... more", PartOfSpeech.NOUN),
                            VocabSeed("木", "もく", "Thursday = もくようび。", "Thursday = もくようび。", PartOfSpeech.NOUN),
                            VocabSeed("木よう日", "もくようび", "Thursday", "Thursday", PartOfSpeech.NOUN),
                            VocabSeed("もしもし", "もしもし", "hello (telephone)", "hello (telephone)", PartOfSpeech.NOUN),
                            VocabSeed("もちろん", "もちろん", "of course", "of course", PartOfSpeech.NOUN),
                            VocabSeed("もちます", "もちます", "have, hold, carry", "have, hold, carry", PartOfSpeech.VERB),
                            VocabSeed("もっていきます", "もっていきます", "take (something) （もってきます。= bring (something)）", "take (something) （もってきます。= bring (something)）", PartOfSpeech.VERB),
                            VocabSeed("もっと", "もっと", "more", "more", PartOfSpeech.NOUN),
                            VocabSeed("もの", "もの", "object, thing", "object, thing", PartOfSpeech.NOUN),
                            VocabSeed("もらいます", "もらいます", "receive", "receive", PartOfSpeech.VERB),
                            VocabSeed("もん", "もん", "gate", "gate", PartOfSpeech.NOUN),
                            VocabSeed("もんだい", "もんだい", "question", "question", PartOfSpeech.NOUN),
                            VocabSeed("もんだいようし", "もんだいようし", "question sheet", "question sheet", PartOfSpeech.NOUN),
                            VocabSeed("もんだいれい", "もんだいれい", "sample question", "sample question", PartOfSpeech.NOUN),
                            VocabSeed("やおや", "やおや", "vegetable store", "vegetable store", PartOfSpeech.NOUN),
                            VocabSeed("やさい", "やさい", "vegetable", "vegetable", PartOfSpeech.NOUN),
                            VocabSeed("このテストは", "やさしい", "easy, kind/nice/sweet/gentle [i-adj", "easy, kind/nice/sweet/gentle [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("やじるし", "やじるし", "arrow", "arrow", PartOfSpeech.NOUN),
                            VocabSeed("安い", "やすい", "cheap, inexpensive", "cheap, inexpensive", PartOfSpeech.NOUN),
                            VocabSeed("休み", "やすみ", "holiday, vacation", "holiday, vacation", PartOfSpeech.NOUN),
                            VocabSeed("休みます", "やすみます", "have a day off, rest, be absent", "have a day off, rest, be absent", PartOfSpeech.VERB),
                            VocabSeed("八つ", "やっつ", "eight", "eight", PartOfSpeech.NOUN),
                            VocabSeed("山", "やま", "mountain", "mountain", PartOfSpeech.NOUN),
                            VocabSeed("やります", "やります", "do", "do", PartOfSpeech.VERB),
                            VocabSeed("ゆうがた", "ゆうがた", "early evening", "early evening", PartOfSpeech.NOUN),
                            VocabSeed("ゆうびんきょく", "ゆうびんきょく", "post office", "post office", PartOfSpeech.NOUN),
                            VocabSeed("有名", "ゆうめい", "famous [na-adj", "famous [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("ゆき", "ゆき", "snow", "snow", PartOfSpeech.NOUN),
                            VocabSeed("ゆっくり(と)", "ゆっくり(と)", "slowly", "slowly", PartOfSpeech.NOUN),
                            VocabSeed("八日", "ようか", "the eight day of the month, eight days", "the eight day of the month, eight days", PartOfSpeech.NOUN),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 19 (721-760)",
                        description = "Vocabulary items #721 to #760 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("ようふく", "ようふく", "(western) clothes", "(western) clothes", PartOfSpeech.NOUN),
                            VocabSeed("よく", "よく", "often", "often", PartOfSpeech.NOUN),
                            VocabSeed("よこ", "よこ", "the side", "the side", PartOfSpeech.NOUN),
                            VocabSeed("四つ", "よっつ", "four", "four", PartOfSpeech.NOUN),
                            VocabSeed("よびます", "よびます", "call, invite", "call, invite", PartOfSpeech.VERB),
                            VocabSeed("読みます", "よみます", "read", "read", PartOfSpeech.VERB),
                            VocabSeed("夜", "よる", "night", "night", PartOfSpeech.NOUN),
                            VocabSeed("ラーメン", "ラーメン", "ramen, noodle", "ramen, noodle", PartOfSpeech.NOUN),
                            VocabSeed("来月", "らいげつ", "next month", "next month", PartOfSpeech.NOUN),
                            VocabSeed("来週", "らいしゅう", "next week", "next week", PartOfSpeech.NOUN),
                            VocabSeed("来年", "らいねん", "next year", "next year", PartOfSpeech.NOUN),
                            VocabSeed("ラジオ", "ラジオ", "radio", "radio", PartOfSpeech.NOUN),
                            VocabSeed("りっぱ", "りっぱ", "good, fine, fine-looking, splendid, magnificent [na-adj", "good, fine, fine-looking, splendid, magnificent [na-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("りゅうがくせい", "りゅうがくせい", "student studying abroad", "student studying abroad", PartOfSpeech.NOUN),
                            VocabSeed("りょうしん", "りょうしん", "parents", "parents", PartOfSpeech.NOUN),
                            VocabSeed("りょうり", "りょうり", "cooking", "cooking", PartOfSpeech.NOUN),
                            VocabSeed("りょこうがいしゃ", "りょこうがいしゃ", "travel agency", "travel agency", PartOfSpeech.NOUN),
                            VocabSeed("りょこうします", "りょこうします", "travel", "travel", PartOfSpeech.VERB),
                            VocabSeed("りんご", "りんご", "apple", "apple", PartOfSpeech.NOUN),
                            VocabSeed("れい", "れい", "example", "example", PartOfSpeech.NOUN),
                            VocabSeed("れいぞうこ", "れいぞうこ", "refrigerator", "refrigerator", PartOfSpeech.NOUN),
                            VocabSeed("レコード", "レコード", "record", "record", PartOfSpeech.NOUN),
                            VocabSeed("レストラン", "レストラン", "restaurant", "restaurant", PartOfSpeech.NOUN),
                            VocabSeed("れんしゅう", "れんしゅう", "practice", "practice", PartOfSpeech.NOUN),
                            VocabSeed("れんしゅうします", "れんしゅうします", "practice", "practice", PartOfSpeech.VERB),
                            VocabSeed("六", "ろく", "six", "six", PartOfSpeech.NOUN),
                            VocabSeed("六本", "ろっぽん", "six (long objects)", "six (long objects)", PartOfSpeech.NOUN),
                            VocabSeed("ワイシャツ", "ワイシャツ", "business shirt (white shirt)", "business shirt (white shirt)", PartOfSpeech.NOUN),
                            VocabSeed("わかい", "わかい", "young [i-adj", "young [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("わかります", "わかります", "understand, know", "understand, know", PartOfSpeech.VERB),
                            VocabSeed("わすれます", "わすれます", "forget", "forget", PartOfSpeech.VERB),
                            VocabSeed("私", "わたくし", "I", "I", PartOfSpeech.NOUN),
                            VocabSeed("私", "わたし", "I", "I", PartOfSpeech.NOUN),
                            VocabSeed("わたします", "わたします", "hand over", "hand over", PartOfSpeech.VERB),
                            VocabSeed("わたります", "わたります", "cross", "cross", PartOfSpeech.VERB),
                            VocabSeed("わるい", "わるい", "bad [i-adj", "bad [i-adj.]", PartOfSpeech.ADJ),
                            VocabSeed("あ", "あ", "Ah!, Oh!", "Ah!, Oh!", PartOfSpeech.INTERJ),
                            VocabSeed("ああ", "ああ", "Ah!", "Ah!", PartOfSpeech.INTERJ),
                            VocabSeed("あの", "あの", "Well, Let me see", "Well, Let me see.", PartOfSpeech.INTERJ),
                            VocabSeed("あのう", "あのう", "Excuse me", "Excuse me., Well, Let me see.", PartOfSpeech.INTERJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 20 (761-800)",
                        description = "Vocabulary items #761 to #800 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("ありがとうございます。", "ありがとうございます。", "Thank you very much", "Thank you very much.", PartOfSpeech.INTERJ),
                            VocabSeed("いいえ。", "いいえ。", "No", "No", PartOfSpeech.INTERJ),
                            VocabSeed("いえ。", "いえ。", "No", "No", PartOfSpeech.INTERJ),
                            VocabSeed("いただきます。", "いただきます。", "Let's eat! (saying this before having a meal", "Let's eat! (saying this before having a meal.)", PartOfSpeech.INTERJ),
                            VocabSeed("いってきます。", "いってきます。", "I am going", "I am going., I am leaving.", PartOfSpeech.INTERJ),
                            VocabSeed("いらっしゃいませ。", "いらっしゃいませ。", "May I help you? (at restaurant, shop)", "May I help you? (at restaurant, shop)", PartOfSpeech.INTERJ),
                            VocabSeed("うーん", "うーん", "Well, Let me see", "Well, Let me see.", PartOfSpeech.INTERJ),
                            VocabSeed("え", "え", "Oh! = えっ。", "Oh! = えっ。", PartOfSpeech.INTERJ),
                            VocabSeed("ええ", "ええ", "Yes", "Yes.", PartOfSpeech.INTERJ),
                            VocabSeed("えー", "えー", "Well, Let me see", "Well, Let me see.", PartOfSpeech.INTERJ),
                            VocabSeed("えっ", "えっ", "Oh! = え。", "Oh! = え。", PartOfSpeech.INTERJ),
                            VocabSeed("おげんきで。", "おげんきで。", "Take care of yourself", "Take care of yourself.", PartOfSpeech.INTERJ),
                            VocabSeed("おねがいします。", "おねがいします。", "Please", "Please.", PartOfSpeech.INTERJ),
                            VocabSeed("おはようございます。", "おはようございます。", "Good morning", "Good morning.", PartOfSpeech.INTERJ),
                            VocabSeed("おやすみなさい。", "おやすみなさい。", "Good night", "Good night.", PartOfSpeech.INTERJ),
                            VocabSeed("ください。", "ください。", "Please give me", "Please give me.", PartOfSpeech.INTERJ),
                            VocabSeed("ごちそうさまでした。", "ごちそうさまでした。", "I've enjoyed my meal very much", "I've enjoyed my meal very much. Thank you. (saying this after having a meal.)", PartOfSpeech.INTERJ),
                            VocabSeed("こちらこそ。", "こちらこそ。", "It is me, not you that", "It is me, not you that ...", PartOfSpeech.INTERJ),
                            VocabSeed("ごめんください。", "ごめんください。", "Hello!, May I come in?", "Hello!, May I come in?", PartOfSpeech.INTERJ),
                            VocabSeed("ごめんなさい。", "ごめんなさい。", "Sorry", "Sorry.", PartOfSpeech.INTERJ),
                            VocabSeed("こんにちは。", "こんにちは。", "Good morning", "Good morning., Good afternoon., Hello.", PartOfSpeech.INTERJ),
                            VocabSeed("こんばんは。", "こんばんは。", "Good evening", "Good evening.", PartOfSpeech.INTERJ),
                            VocabSeed("さあ…", "さあ…", "Well", "Well ...", PartOfSpeech.INTERJ),
                            VocabSeed("さようなら。", "さようなら。", "Goodbye", "Goodbye.", PartOfSpeech.INTERJ),
                            VocabSeed("しつれいしました。", "しつれいしました。", "I am sorry", "I am sorry. (I am sorry to have been rude.)", PartOfSpeech.INTERJ),
                            VocabSeed("しつれいします。", "しつれいします。", "Excuse me", "Excuse me.", PartOfSpeech.INTERJ),
                            VocabSeed("じゃ", "じゃ", "then, well, well then, if so, in the case", "then, well, well then, if so, in the case.", PartOfSpeech.INTERJ),
                            VocabSeed("じゃあ", "じゃあ", "then, well, well then, if so, in the case", "then, well, well then, if so, in the case.", PartOfSpeech.INTERJ),
                            VocabSeed("すみません。", "すみません。", "Excuse me", "Excuse me.", PartOfSpeech.INTERJ),
                            VocabSeed("そうしましょう。", "そうしましょう。", "Let's do it", "Let's do it.", PartOfSpeech.INTERJ),
                            VocabSeed("そうです。", "そうです。", "That's right", "That's right.", PartOfSpeech.INTERJ),
                            VocabSeed("そうですか。", "そうですか。", "I see", "I see.", PartOfSpeech.INTERJ),
                            VocabSeed("そうですね。", "そうですね。", "Oh right", "Oh right., Well ...", PartOfSpeech.INTERJ),
                            VocabSeed("ただいま。", "ただいま。", "I'm home", "I'm home., I'm back.", PartOfSpeech.INTERJ),
                            VocabSeed("では、また。", "では、また。", "Well then, see you again", "Well then, see you again.", PartOfSpeech.INTERJ),
                            VocabSeed("どういたしまして。", "どういたしまして。", "You are welcome", "You are welcome., Not at all.", PartOfSpeech.INTERJ),
                            VocabSeed("どうぞ。", "どうぞ。", "Please", "Please.", PartOfSpeech.INTERJ),
                            VocabSeed("どうも。", "どうも。", "Thanks", "Thanks.", PartOfSpeech.INTERJ),
                            VocabSeed("どうもありがとう。", "どうもありがとう。", "Thanks a lot", "Thanks a lot.", PartOfSpeech.INTERJ),
                            VocabSeed("はい。", "はい。", "Yes", "Yes.", PartOfSpeech.INTERJ),
                        ),
                    ),
                    CourseSeed(
                        title = "Set 21 (801-802)",
                        description = "Vocabulary items #801 to #802 from the JLPT N5 PDF list.",
                        vocabularies = listOf(
                            VocabSeed("はじめまして。", "はじめまして。", "Nice to see you", "Nice to see you.", PartOfSpeech.INTERJ),
                            VocabSeed("よろしく。", "よろしく。", "(Please favor me", "(Please favor me.)", PartOfSpeech.INTERJ),
                        ),
                    ),
                ),
            ),
        )

        seedSyllabusContent(publicSyllabus, topicSeeds)

        return publicSyllabus
    }
}
